from __future__ import annotations

COURSE_TYPE_ACADEMIC = "academic"
COURSE_TYPE_AUTHOR = "author"
COURSE_TYPE_EXAM_PREP = "exam_prep"
COURSE_TYPE_INTENSIVE = "intensive"
COURSE_TYPE_CLUB = "club"
COURSE_TYPE_ELECTIVE = "elective"

COURSE_TYPE_CODES = frozenset(
    {
        COURSE_TYPE_ACADEMIC,
        COURSE_TYPE_AUTHOR,
        COURSE_TYPE_EXAM_PREP,
        COURSE_TYPE_INTENSIVE,
        COURSE_TYPE_CLUB,
        COURSE_TYPE_ELECTIVE,
    }
)

COURSE_ORIGIN_MANUAL = "manual"
COURSE_ORIGIN_KTP_IMPORT = "ktp_import"
COURSE_ORIGIN_EDUCATION_LOAD = "education_load"
COURSE_ORIGIN_TEMPLATE = "template"

COURSE_ORIGIN_CODES = frozenset(
    {
        COURSE_ORIGIN_MANUAL,
        COURSE_ORIGIN_KTP_IMPORT,
        COURSE_ORIGIN_EDUCATION_LOAD,
        COURSE_ORIGIN_TEMPLATE,
    }
)

COURSE_STATUS_DRAFT = "draft"
COURSE_STATUS_PUBLISHED = "published"
COURSE_STATUS_ARCHIVED = "archived"

COURSE_STATUS_CODES = frozenset(
    {
        COURSE_STATUS_DRAFT,
        COURSE_STATUS_PUBLISHED,
        COURSE_STATUS_ARCHIVED,
    }
)

COURSE_VISIBILITY_PRIVATE = "private"
COURSE_VISIBILITY_ASSIGNED_ONLY = "assigned_only"
COURSE_VISIBILITY_ORGANIZATION = "organization"
COURSE_VISIBILITY_PUBLIC_LINK = "public_link"

COURSE_VISIBILITY_CODES = frozenset(
    {
        COURSE_VISIBILITY_PRIVATE,
        COURSE_VISIBILITY_ASSIGNED_ONLY,
        COURSE_VISIBILITY_ORGANIZATION,
        COURSE_VISIBILITY_PUBLIC_LINK,
    }
)

COURSE_PLAN_STATUS_DRAFT = "draft"
COURSE_PLAN_STATUS_IMPORTED = "imported"
COURSE_PLAN_STATUS_REVIEWED = "reviewed"
COURSE_PLAN_STATUS_APPROVED = "approved"
COURSE_PLAN_STATUS_ARCHIVED = "archived"

COURSE_PLAN_STATUS_CODES = frozenset(
    {
        COURSE_PLAN_STATUS_DRAFT,
        COURSE_PLAN_STATUS_IMPORTED,
        COURSE_PLAN_STATUS_REVIEWED,
        COURSE_PLAN_STATUS_APPROVED,
        COURSE_PLAN_STATUS_ARCHIVED,
    }
)

COURSE_PLAN_IMPORT_STATUS_UPLOADED = "uploaded"
COURSE_PLAN_IMPORT_STATUS_PARSED = "parsed"
COURSE_PLAN_IMPORT_STATUS_FAILED = "failed"
COURSE_PLAN_IMPORT_STATUS_APPLIED = "applied"

COURSE_PLAN_IMPORT_STATUS_CODES = frozenset(
    {
        COURSE_PLAN_IMPORT_STATUS_UPLOADED,
        COURSE_PLAN_IMPORT_STATUS_PARSED,
        COURSE_PLAN_IMPORT_STATUS_FAILED,
        COURSE_PLAN_IMPORT_STATUS_APPLIED,
    }
)

COURSE_GROUP_VISIBILITY_HIDDEN = "hidden"
COURSE_GROUP_VISIBILITY_VISIBLE = "visible"
COURSE_GROUP_VISIBILITY_ARCHIVED = "archived"

COURSE_GROUP_VISIBILITY_CODES = frozenset(
    {
        COURSE_GROUP_VISIBILITY_HIDDEN,
        COURSE_GROUP_VISIBILITY_VISIBLE,
        COURSE_GROUP_VISIBILITY_ARCHIVED,
    }
)

COURSE_ACCESS_TYPE_LEARNER = "learner"
COURSE_ACCESS_TYPE_ORGANIZATION = "organization"
COURSE_ACCESS_TYPE_PUBLIC_LINK = "public_link"
COURSE_ACCESS_TYPE_INVITE_CODE = "invite_code"

COURSE_ACCESS_TYPE_CODES = frozenset(
    {
        COURSE_ACCESS_TYPE_LEARNER,
        COURSE_ACCESS_TYPE_ORGANIZATION,
        COURSE_ACCESS_TYPE_PUBLIC_LINK,
        COURSE_ACCESS_TYPE_INVITE_CODE,
    }
)

LESSON_TYPE_LESSON = "lesson"
LESSON_TYPE_LECTURE = "lecture"
LESSON_TYPE_PRACTICE = "practice"
LESSON_TYPE_LAB = "lab"
LESSON_TYPE_SEMINAR = "seminar"
LESSON_TYPE_CONTROL = "control"
LESSON_TYPE_CONSULTATION = "consultation"
LESSON_TYPE_INDEPENDENT = "independent"
LESSON_TYPE_OTHER = "other"

LESSON_TYPE_CODES = frozenset(
    {
        LESSON_TYPE_LESSON,
        LESSON_TYPE_LECTURE,
        LESSON_TYPE_PRACTICE,
        LESSON_TYPE_LAB,
        LESSON_TYPE_SEMINAR,
        LESSON_TYPE_CONTROL,
        LESSON_TYPE_CONSULTATION,
        LESSON_TYPE_INDEPENDENT,
        LESSON_TYPE_OTHER,
    }
)

LESSON_BLOCK_TYPE_TEXT = "text"
LESSON_BLOCK_TYPE_VIDEO = "video"
LESSON_BLOCK_TYPE_FILE = "file"
LESSON_BLOCK_TYPE_LINK = "link"
LESSON_BLOCK_TYPE_IMAGE = "image"
LESSON_BLOCK_TYPE_PRESENTATION = "presentation"
LESSON_BLOCK_TYPE_CODE = "code"
LESSON_BLOCK_TYPE_EMBED = "embed"
LESSON_BLOCK_TYPE_MATERIAL = "material"
LESSON_BLOCK_TYPE_ASSIGNMENT_PLACEHOLDER = "assignment_placeholder"

LESSON_BLOCK_TYPE_CODES = frozenset(
    {
        LESSON_BLOCK_TYPE_TEXT,
        LESSON_BLOCK_TYPE_VIDEO,
        LESSON_BLOCK_TYPE_FILE,
        LESSON_BLOCK_TYPE_LINK,
        LESSON_BLOCK_TYPE_IMAGE,
        LESSON_BLOCK_TYPE_PRESENTATION,
        LESSON_BLOCK_TYPE_CODE,
        LESSON_BLOCK_TYPE_EMBED,
        LESSON_BLOCK_TYPE_MATERIAL,
        LESSON_BLOCK_TYPE_ASSIGNMENT_PLACEHOLDER,
    }
)

COURSE_MATERIAL_PLACEMENT_COURSE = "course"
COURSE_MATERIAL_PLACEMENT_SECTION = "section"
COURSE_MATERIAL_PLACEMENT_LESSON = "lesson"

COURSE_MATERIAL_PLACEMENT_CODES = frozenset(
    {
        COURSE_MATERIAL_PLACEMENT_COURSE,
        COURSE_MATERIAL_PLACEMENT_SECTION,
        COURSE_MATERIAL_PLACEMENT_LESSON,
    }
)

COURSE_ENROLLMENT_STATUS_ENROLLED = "enrolled"
COURSE_ENROLLMENT_STATUS_IN_PROGRESS = "in_progress"
COURSE_ENROLLMENT_STATUS_COMPLETED = "completed"
COURSE_ENROLLMENT_STATUS_CANCELLED = "cancelled"
COURSE_ENROLLMENT_STATUS_ARCHIVED = "archived"

COURSE_ENROLLMENT_STATUS_CODES = frozenset(
    {
        COURSE_ENROLLMENT_STATUS_ENROLLED,
        COURSE_ENROLLMENT_STATUS_IN_PROGRESS,
        COURSE_ENROLLMENT_STATUS_COMPLETED,
        COURSE_ENROLLMENT_STATUS_CANCELLED,
        COURSE_ENROLLMENT_STATUS_ARCHIVED,
    }
)

ACTIVE_COURSE_ENROLLMENT_STATUS_CODES = frozenset(
    {
        COURSE_ENROLLMENT_STATUS_ENROLLED,
        COURSE_ENROLLMENT_STATUS_IN_PROGRESS,
    }
)

FINISHED_COURSE_ENROLLMENT_STATUS_CODES = frozenset(
    {
        COURSE_ENROLLMENT_STATUS_COMPLETED,
        COURSE_ENROLLMENT_STATUS_CANCELLED,
        COURSE_ENROLLMENT_STATUS_ARCHIVED,
    }
)

LESSON_PROGRESS_STATUS_NOT_STARTED = "not_started"
LESSON_PROGRESS_STATUS_IN_PROGRESS = "in_progress"
LESSON_PROGRESS_STATUS_COMPLETED = "completed"
LESSON_PROGRESS_STATUS_SKIPPED = "skipped"

LESSON_PROGRESS_STATUS_CODES = frozenset(
    {
        LESSON_PROGRESS_STATUS_NOT_STARTED,
        LESSON_PROGRESS_STATUS_IN_PROGRESS,
        LESSON_PROGRESS_STATUS_COMPLETED,
        LESSON_PROGRESS_STATUS_SKIPPED,
    }
)

FINISHED_LESSON_PROGRESS_STATUS_CODES = frozenset(
    {
        LESSON_PROGRESS_STATUS_COMPLETED,
        LESSON_PROGRESS_STATUS_SKIPPED,
    }
)
