from __future__ import annotations

COURSE_CODE_MAX_LENGTH = 64
COURSE_SLUG_MAX_LENGTH = 120
COURSE_TITLE_MAX_LENGTH = 255
COURSE_SUBTITLE_MAX_LENGTH = 255
COURSE_STATUS_MAX_LENGTH = 32
COURSE_TYPE_MAX_LENGTH = 32
COURSE_VISIBILITY_MAX_LENGTH = 32
COURSE_ORIGIN_MAX_LENGTH = 32
COURSE_LANGUAGE_MAX_LENGTH = 16
COURSE_LEVEL_MAX_LENGTH = 64

DEFAULT_COURSE_LANGUAGE = "ru"
DEFAULT_PROGRESS_PERCENT = 0
MIN_PROGRESS_PERCENT = 0
MAX_PROGRESS_PERCENT = 100

DEFAULT_ORDER = 1
DEFAULT_HOURS = 0
DEFAULT_SPENT_MINUTES = 0
DEFAULT_ATTEMPTS_COUNT = 0


COURSE_PLAN_DISCIPLINE_NAME_MAX_LENGTH = 255
COURSE_PLAN_DISCIPLINE_CODE_MAX_LENGTH = 64
COURSE_PLAN_SPECIALTY_CODE_MAX_LENGTH = 64
COURSE_PLAN_SPECIALTY_NAME_MAX_LENGTH = 255
COURSE_PLAN_TEACHER_NAME_MAX_LENGTH = 255
COURSE_PLAN_ORGANIZATION_NAME_MAX_LENGTH = 255
COURSE_PLAN_ACADEMIC_YEAR_LABEL_MAX_LENGTH = 32
COURSE_PLAN_COMMISSION_NAME_MAX_LENGTH = 255
COURSE_PLAN_PROTOCOL_NUMBER_MAX_LENGTH = 64
COURSE_PLAN_APPROVED_ORDER_NUMBER_MAX_LENGTH = 64
COURSE_PLAN_STATUS_MAX_LENGTH = 32


COURSE_PLAN_IMPORT_STATUS_MAX_LENGTH = 32
COURSE_PLAN_IMPORT_FILENAME_MAX_LENGTH = 255
COURSE_PLAN_IMPORT_FILE_HASH_MAX_LENGTH = 128
COURSE_PLAN_IMPORT_PARSER_VERSION_MAX_LENGTH = 64


COURSE_ACCESS_TYPE_MAX_LENGTH = 32
COURSE_GROUP_VISIBILITY_MAX_LENGTH = 32
COURSE_ACCESS_CODE_MAX_LENGTH = 64


COURSE_SECTION_TITLE_MAX_LENGTH = 255
COURSE_LESSON_TITLE_MAX_LENGTH = 255
COURSE_LESSON_TYPE_MAX_LENGTH = 32
COURSE_LESSON_BLOCK_TITLE_MAX_LENGTH = 255
COURSE_LESSON_BLOCK_TYPE_MAX_LENGTH = 32
COURSE_MATERIAL_PLACEMENT_MAX_LENGTH = 32


COURSE_ENROLLMENT_STATUS_MAX_LENGTH = 32
LESSON_PROGRESS_STATUS_MAX_LENGTH = 32

MIN_HOURS_VALUE = 0
MAX_HOURS_VALUE = 10_000

MIN_ORDER_VALUE = 1
MAX_ORDER_VALUE = 100_000

MIN_SCORE_VALUE = 0
MAX_SCORE_VALUE = 100
