from __future__ import annotations

MATERIAL_TYPE_FILE = "file"
MATERIAL_TYPE_LINK = "link"
MATERIAL_TYPE_TEXT = "text"
MATERIAL_TYPE_VIDEO = "video"
MATERIAL_TYPE_IMAGE = "image"
MATERIAL_TYPE_PRESENTATION = "presentation"
MATERIAL_TYPE_DOCUMENT = "document"
MATERIAL_TYPE_SPREADSHEET = "spreadsheet"
MATERIAL_TYPE_ARCHIVE = "archive"
MATERIAL_TYPE_CODE = "code"
MATERIAL_TYPE_EMBED = "embed"
MATERIAL_TYPE_OTHER = "other"

MATERIAL_TYPE_CODES = frozenset(
    {
        MATERIAL_TYPE_FILE,
        MATERIAL_TYPE_LINK,
        MATERIAL_TYPE_TEXT,
        MATERIAL_TYPE_VIDEO,
        MATERIAL_TYPE_IMAGE,
        MATERIAL_TYPE_PRESENTATION,
        MATERIAL_TYPE_DOCUMENT,
        MATERIAL_TYPE_SPREADSHEET,
        MATERIAL_TYPE_ARCHIVE,
        MATERIAL_TYPE_CODE,
        MATERIAL_TYPE_EMBED,
        MATERIAL_TYPE_OTHER,
    }
)


MATERIAL_STATUS_DRAFT = "draft"
MATERIAL_STATUS_PUBLISHED = "published"
MATERIAL_STATUS_ARCHIVED = "archived"

MATERIAL_STATUS_CODES = frozenset(
    {
        MATERIAL_STATUS_DRAFT,
        MATERIAL_STATUS_PUBLISHED,
        MATERIAL_STATUS_ARCHIVED,
    }
)


MATERIAL_VISIBILITY_PRIVATE = "private"
MATERIAL_VISIBILITY_ORGANIZATION = "organization"
MATERIAL_VISIBILITY_ASSIGNED_ONLY = "assigned_only"
MATERIAL_VISIBILITY_PUBLIC = "public"

MATERIAL_VISIBILITY_CODES = frozenset(
    {
        MATERIAL_VISIBILITY_PRIVATE,
        MATERIAL_VISIBILITY_ORGANIZATION,
        MATERIAL_VISIBILITY_ASSIGNED_ONLY,
        MATERIAL_VISIBILITY_PUBLIC,
    }
)


MATERIAL_SOURCE_MANUAL = "manual"
MATERIAL_SOURCE_UPLOAD = "upload"
MATERIAL_SOURCE_IMPORT = "import"
MATERIAL_SOURCE_EXTERNAL = "external"
MATERIAL_SOURCE_COURSE = "course"

MATERIAL_SOURCE_CODES = frozenset(
    {
        MATERIAL_SOURCE_MANUAL,
        MATERIAL_SOURCE_UPLOAD,
        MATERIAL_SOURCE_IMPORT,
        MATERIAL_SOURCE_EXTERNAL,
        MATERIAL_SOURCE_COURSE,
    }
)


MATERIAL_VERSION_STATUS_DRAFT = "draft"
MATERIAL_VERSION_STATUS_CURRENT = "current"
MATERIAL_VERSION_STATUS_ARCHIVED = "archived"

MATERIAL_VERSION_STATUS_CODES = frozenset(
    {
        MATERIAL_VERSION_STATUS_DRAFT,
        MATERIAL_VERSION_STATUS_CURRENT,
        MATERIAL_VERSION_STATUS_ARCHIVED,
    }
)


MATERIAL_USAGE_ACTION_VIEW = "view"
MATERIAL_USAGE_ACTION_DOWNLOAD = "download"
MATERIAL_USAGE_ACTION_OPEN_LINK = "open_link"
MATERIAL_USAGE_ACTION_ATTACH = "attach"
MATERIAL_USAGE_ACTION_DETACH = "detach"
MATERIAL_USAGE_ACTION_UPDATE = "update"
MATERIAL_USAGE_ACTION_CREATE_VERSION = "create_version"
MATERIAL_USAGE_ACTION_PUBLISH = "publish"
MATERIAL_USAGE_ACTION_ARCHIVE = "archive"

MATERIAL_USAGE_ACTION_CODES = frozenset(
    {
        MATERIAL_USAGE_ACTION_VIEW,
        MATERIAL_USAGE_ACTION_DOWNLOAD,
        MATERIAL_USAGE_ACTION_OPEN_LINK,
        MATERIAL_USAGE_ACTION_ATTACH,
        MATERIAL_USAGE_ACTION_DETACH,
        MATERIAL_USAGE_ACTION_UPDATE,
        MATERIAL_USAGE_ACTION_CREATE_VERSION,
        MATERIAL_USAGE_ACTION_PUBLISH,
        MATERIAL_USAGE_ACTION_ARCHIVE,
    }
)


MATERIAL_USAGE_CONTEXT_LIBRARY = "library"
MATERIAL_USAGE_CONTEXT_COURSE = "course"
MATERIAL_USAGE_CONTEXT_LESSON = "lesson"
MATERIAL_USAGE_CONTEXT_ASSIGNMENT = "assignment"
MATERIAL_USAGE_CONTEXT_PROFILE = "profile"
MATERIAL_USAGE_CONTEXT_ADMIN = "admin"
MATERIAL_USAGE_CONTEXT_OTHER = "other"

MATERIAL_USAGE_CONTEXT_CODES = frozenset(
    {
        MATERIAL_USAGE_CONTEXT_LIBRARY,
        MATERIAL_USAGE_CONTEXT_COURSE,
        MATERIAL_USAGE_CONTEXT_LESSON,
        MATERIAL_USAGE_CONTEXT_ASSIGNMENT,
        MATERIAL_USAGE_CONTEXT_PROFILE,
        MATERIAL_USAGE_CONTEXT_ADMIN,
        MATERIAL_USAGE_CONTEXT_OTHER,
    }
)
