from __future__ import annotations

MATERIAL_TITLE_MAX_LENGTH = 255
MATERIAL_SLUG_MAX_LENGTH = 120
MATERIAL_TYPE_MAX_LENGTH = 32
MATERIAL_STATUS_MAX_LENGTH = 32
MATERIAL_VISIBILITY_MAX_LENGTH = 32
MATERIAL_SOURCE_MAX_LENGTH = 32

MATERIAL_TAG_MAX_LENGTH = 64
MATERIAL_TAGS_MAX_COUNT = 20

MATERIAL_SHORT_DESCRIPTION_MAX_LENGTH = 500
MATERIAL_EXTERNAL_URL_MAX_LENGTH = 1000

DEFAULT_MATERIAL_VERSION_NUMBER = 1


MATERIAL_CATEGORY_NAME_MAX_LENGTH = 255
MATERIAL_CATEGORY_SLUG_MAX_LENGTH = 120


MATERIAL_VERSION_STATUS_MAX_LENGTH = 32
MATERIAL_VERSION_MIME_TYPE_MAX_LENGTH = 128
MATERIAL_VERSION_CHECKSUM_MAX_LENGTH = 128
MATERIAL_VERSION_CHANGE_LOG_MAX_LENGTH = 1000

MATERIAL_ORIGINAL_FILENAME_MAX_LENGTH = 255

MIN_MATERIAL_VERSION_NUMBER = 1
MAX_MATERIAL_VERSION_NUMBER = 100_000


MIN_FILE_SIZE_BYTES = 0
MAX_FILE_SIZE_BYTES = 200 * 1024 * 1024

MATERIAL_FILE_UPLOAD_TO = "materials/files/"
MATERIAL_PREVIEW_UPLOAD_TO = "materials/previews/"


MATERIAL_USAGE_ACTION_MAX_LENGTH = 32
MATERIAL_USAGE_CONTEXT_MAX_LENGTH = 32
MATERIAL_USAGE_IP_ADDRESS_MAX_LENGTH = 64
MATERIAL_USAGE_USER_AGENT_MAX_LENGTH = 512


DEFAULT_ORDER = 1
MIN_ORDER_VALUE = 1
MAX_ORDER_VALUE = 100_000
