import type { RouteRecordRaw } from "vue-router";

export const teacherRoutes: RouteRecordRaw[] = [
    {
        path: "/teacher",
        name: "teacher-dashboard",
        component: () => import("@/modules/teacher/pages/TeacherDashboardPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Кабинет преподавателя | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/courses",
        name: "teacher-courses",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Мои курсы | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/courses/:id",
        name: "teacher-course-detail",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Курс преподавателя | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/courses/:id/edit",
        name: "teacher-course-edit",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Редактирование курса | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/courses/:id/analytics",
        name: "teacher-course-analytics",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Аналитика курса | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/lessons",
        name: "teacher-lessons",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Уроки | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/lessons/create",
        name: "teacher-lessons-create",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Создание урока | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/tests",
        name: "teacher-tests",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Тесты | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/tests/create",
        name: "teacher-tests-create",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Создание теста | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/practice",
        name: "teacher-practice",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Практические работы | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/homework",
        name: "teacher-homework",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Домашние задания | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/homework/create",
        name: "teacher-homework-create",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Создание домашнего задания | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/journal",
        name: "teacher-journal",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Журнал | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/analytics",
        name: "teacher-analytics",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Аналитика преподавателя | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/feedback",
        name: "teacher-feedback",
        component: () => import("@/modules/feedback/pages/FeedbackPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Обращения преподавателя | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/calendar",
        name: "teacher-calendar",
        component: () => import("@/modules/calendar/pages/CalendarPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Календарь преподавателя | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/notes",
        name: "teacher-notes",
        component: () => import("@/modules/notes/pages/NotesPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Заметки преподавателя | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/security",
        name: "teacher-security",
        component: () => import("@/components/dashboard/shared/DashboardPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Безопасность преподавателя | Пифагор",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
];
