import type { RouteRecordRaw } from "vue-router";

export const teacherRoutes: RouteRecordRaw[] = [
    {
        path: "/teacher",
        name: "teacher-dashboard",
        component: () => import("@/modules/teacher/pages/TeacherDashboardPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Кабинет преподавателя — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/profile",
        name: "teacher-profile",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Профиль преподавателя — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/courses",
        name: "teacher-courses",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Мои курсы — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/courses/:id",
        name: "teacher-course-detail",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Курс преподавателя — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/courses/:id/edit",
        name: "teacher-course-edit",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Редактирование курса — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/courses/:id/analytics",
        name: "teacher-course-analytics",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Аналитика курса — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/lessons",
        name: "teacher-lessons",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Уроки — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/lessons/create",
        name: "teacher-lessons-create",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Создание урока — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/tests",
        name: "teacher-tests",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Тесты — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/tests/create",
        name: "teacher-tests-create",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Создание теста — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/practice",
        name: "teacher-practice",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Практические работы — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/homework",
        name: "teacher-homework",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Домашние задания — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/homework/create",
        name: "teacher-homework-create",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Создание домашнего задания — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/journal",
        name: "teacher-journal",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Журнал — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/analytics",
        name: "teacher-analytics",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Аналитика преподавателя — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/calendar",
        name: "teacher-calendar",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Календарь преподавателя — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/notes",
        name: "teacher-notes",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Заметки преподавателя — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/notifications",
        name: "teacher-notifications",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Уведомления преподавателя — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/settings",
        name: "teacher-settings",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Настройки преподавателя — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
    {
        path: "/teacher/security",
        name: "teacher-security",
        component: () => import("@/modules/teacher/pages/TeacherPlaceholderPage.vue"),
        meta: {
            requiresAuth: true,
            title: "Безопасность преподавателя — ЦОС «Пифагор»",
            layout: "dashboard",
            roles: [
                "teacher",
                "curator",
                "methodist",
                "organizer",
                "mentor",
            ],
        },
    },
];
