# Generated by Django 5.2.14 on 2026-06-08 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0002_initial"),
        ("organizations", "0003_groupcurator_teacherorganization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Инструкция"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликован"),
                            ("archived", "Архивирован"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Только преподавателю"),
                            ("course", "Участникам курса"),
                            ("groups", "Назначенным группам"),
                        ],
                        default="course",
                        max_length=32,
                        verbose_name="Видимость",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Максимум попыток"
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ограничение времени, минут"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Максимальный балл"
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Проходной балл"
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False, verbose_name="Перемешивать вопросы"
                    ),
                ),
                (
                    "shuffle_options",
                    models.BooleanField(
                        default=False, verbose_name="Перемешивать варианты"
                    ),
                ),
                (
                    "show_correct_answers_after_publish",
                    models.BooleanField(
                        default=False,
                        verbose_name="Показывать правильные ответы после публикации",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата архивирования"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="course.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests",
                        to="course.courselesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "lesson_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tests",
                        to="course.courselessonblock",
                        verbose_name="Блок урока",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tests",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "owner_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Преподаватель-владелец",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tests",
                        to="organizations.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(verbose_name="Номер попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Начата"),
                            ("submitted", "Отправлена"),
                            ("auto_checked", "Проверена автоматически"),
                            ("needs_review", "Ожидает проверки преподавателем"),
                            ("confirmed", "Оценка подтверждена"),
                            ("published", "Результат опубликован"),
                            ("cancelled", "Отменена"),
                        ],
                        default="started",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "check_status",
                    models.CharField(
                        choices=[
                            ("not_checked", "Не проверено"),
                            ("auto_checked", "Проверено автоматически"),
                            ("needs_review", "Требует ручной проверки"),
                            ("checked", "Проверено"),
                        ],
                        default="not_checked",
                        max_length=32,
                        verbose_name="Статус проверки",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "auto_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата автопроверки"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата проверки преподавателем",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата подтверждения оценки"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации результата"
                    ),
                ),
                (
                    "auto_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Автоматический балл",
                    ),
                ),
                (
                    "teacher_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Балл преподавателя",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Итоговый балл",
                    ),
                ),
                (
                    "auto_grade",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Автоматическая оценка"
                    ),
                ),
                (
                    "teacher_grade",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Оценка преподавателя"
                    ),
                ),
                (
                    "final_grade",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Итоговая оценка"
                    ),
                ),
                (
                    "requires_manual_review",
                    models.BooleanField(
                        default=False, verbose_name="Требует ручной проверки"
                    ),
                ),
                (
                    "is_confirmed_by_teacher",
                    models.BooleanField(
                        default=False, verbose_name="Оценка подтверждена преподавателем"
                    ),
                ),
                (
                    "is_visible_to_learner",
                    models.BooleanField(
                        default=False, verbose_name="Видно обучающемуся"
                    ),
                ),
                (
                    "is_visible_to_guardian",
                    models.BooleanField(default=False, verbose_name="Видно родителю"),
                ),
                (
                    "teacher_comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий преподавателя"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обучающийся",
                    ),
                ),
                (
                    "reviewer_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_test_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверил преподаватель",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="testing.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка теста",
                "verbose_name_plural": "Попытки тестов",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="TestLearnerResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активен"),
                            ("blocked", "Повторное прохождение заблокировано"),
                            ("archived", "Архивирован"),
                        ],
                        default="active",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "grade_source",
                    models.CharField(
                        choices=[
                            ("auto", "Автоматически рассчитана"),
                            ("teacher", "Подтверждена преподавателем"),
                            ("average", "Средняя по попыткам"),
                        ],
                        default="average",
                        max_length=32,
                        verbose_name="Источник оценки",
                    ),
                ),
                (
                    "confirmed_attempts_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Количество подтверждённых попыток"
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Количество попыток"
                    ),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Средний балл",
                    ),
                ),
                (
                    "average_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Средняя оценка",
                    ),
                ),
                (
                    "best_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Лучший балл",
                    ),
                ),
                (
                    "best_grade",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Лучшая оценка"
                    ),
                ),
                (
                    "is_passed",
                    models.BooleanField(default=False, verbose_name="Тест пройден"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        verbose_name="Повторное прохождение заблокировано",
                    ),
                ),
                (
                    "is_visible_to_learner",
                    models.BooleanField(
                        default=False, verbose_name="Видно обучающемуся"
                    ),
                ),
                (
                    "is_visible_to_guardian",
                    models.BooleanField(default=False, verbose_name="Видно родителю"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "last_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="result_as_last_attempt",
                        to="testing.testattempt",
                        verbose_name="Последняя попытка",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обучающийся",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_results",
                        to="testing.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Итоговый результат теста",
                "verbose_name_plural": "Итоговые результаты тестов",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Один вариант ответа"),
                            ("multiple_choice", "Несколько вариантов ответа"),
                            ("true_false", "Верно / неверно"),
                            ("short_text", "Короткий текстовый ответ"),
                            ("number", "Числовой ответ"),
                        ],
                        default="single_choice",
                        max_length=32,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "check_mode",
                    models.CharField(
                        choices=[
                            ("auto", "Автоматическая проверка"),
                            ("manual", "Ручная проверка"),
                            ("semi_auto", "Полуавтоматическая проверка"),
                        ],
                        default="auto",
                        max_length=32,
                        verbose_name="Режим проверки",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Краткое название"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                ("explanation", models.TextField(blank=True, verbose_name="Пояснение")),
                (
                    "expected_text_answer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Ожидаемый текстовый ответ",
                    ),
                ),
                (
                    "expected_number_answer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Ожидаемый числовой ответ",
                    ),
                ),
                (
                    "case_sensitive",
                    models.BooleanField(
                        default=False, verbose_name="Учитывать регистр"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Порядок"),
                ),
                ("score", models.PositiveIntegerField(default=1, verbose_name="Балл")),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Обязательный"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="testing.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос теста",
                "verbose_name_plural": "Вопросы тестов",
                "ordering": ("test_id", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TestQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст варианта")),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильный ответ"),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Балл за вариант",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Пояснение к варианту"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="testing.testquestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
                "ordering": ("question_id", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TestAttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_options_data",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Выбранные варианты"
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(blank=True, verbose_name="Текстовый ответ"),
                ),
                (
                    "number_answer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Числовой ответ",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Ответ верный"
                    ),
                ),
                (
                    "auto_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Автоматический балл",
                    ),
                ),
                (
                    "teacher_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Балл преподавателя",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Итоговый балл",
                    ),
                ),
                (
                    "requires_manual_review",
                    models.BooleanField(
                        default=False, verbose_name="Требует ручной проверки"
                    ),
                ),
                (
                    "teacher_comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий преподавателя"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="testing.testattempt",
                        verbose_name="Попытка",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempt_answers",
                        to="testing.testquestion",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="single_attempt_answers",
                        to="testing.testquestionoption",
                        verbose_name="Выбранный вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на вопрос теста",
                "verbose_name_plural": "Ответы на вопросы тестов",
                "ordering": ("attempt_id", "question_id", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["status"], name="tst_test_status_idx"),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["visibility"], name="tst_test_vis_idx"),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["course"], name="tst_test_course_idx"),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["lesson"], name="tst_test_lesson_idx"),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["organization"], name="tst_test_org_idx"),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["subject"], name="tst_test_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["owner_teacher"], name="tst_test_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["is_active"], name="tst_test_active_idx"),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["test", "learner"], name="tst_attempt_test_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(fields=["status"], name="tst_attempt_status_idx"),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(fields=["check_status"], name="tst_attempt_check_idx"),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["is_confirmed_by_teacher"], name="tst_attempt_confirm_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(
                fields=["is_visible_to_learner"], name="tst_attempt_visible_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="testattempt",
            constraint=models.UniqueConstraint(
                fields=("test", "learner", "attempt_number"),
                name="uq_tst_attempt_number",
            ),
        ),
        migrations.AddIndex(
            model_name="testlearnerresult",
            index=models.Index(
                fields=["test", "learner"], name="tst_result_test_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testlearnerresult",
            index=models.Index(fields=["status"], name="tst_result_status_idx"),
        ),
        migrations.AddIndex(
            model_name="testlearnerresult",
            index=models.Index(fields=["is_blocked"], name="tst_result_blocked_idx"),
        ),
        migrations.AddIndex(
            model_name="testlearnerresult",
            index=models.Index(
                fields=["is_visible_to_learner"], name="tst_result_visible_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="testlearnerresult",
            constraint=models.UniqueConstraint(
                fields=("test", "learner"), name="uq_tst_result_learner"
            ),
        ),
        migrations.AddIndex(
            model_name="testquestion",
            index=models.Index(fields=["test"], name="tst_question_test_idx"),
        ),
        migrations.AddIndex(
            model_name="testquestion",
            index=models.Index(fields=["question_type"], name="tst_question_type_idx"),
        ),
        migrations.AddIndex(
            model_name="testquestion",
            index=models.Index(fields=["check_mode"], name="tst_question_check_idx"),
        ),
        migrations.AddIndex(
            model_name="testquestion",
            index=models.Index(fields=["is_active"], name="tst_question_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="testquestion",
            constraint=models.UniqueConstraint(
                fields=("test", "order"), name="uq_tst_question_order"
            ),
        ),
        migrations.AddIndex(
            model_name="testquestionoption",
            index=models.Index(fields=["question"], name="tst_option_question_idx"),
        ),
        migrations.AddIndex(
            model_name="testquestionoption",
            index=models.Index(fields=["is_correct"], name="tst_option_correct_idx"),
        ),
        migrations.AddIndex(
            model_name="testquestionoption",
            index=models.Index(fields=["is_active"], name="tst_option_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="testquestionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="uq_tst_option_order"
            ),
        ),
        migrations.AddIndex(
            model_name="testattemptanswer",
            index=models.Index(fields=["attempt"], name="tst_answer_attempt_idx"),
        ),
        migrations.AddIndex(
            model_name="testattemptanswer",
            index=models.Index(fields=["question"], name="tst_answer_question_idx"),
        ),
        migrations.AddIndex(
            model_name="testattemptanswer",
            index=models.Index(
                fields=["selected_option"], name="tst_answer_option_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testattemptanswer",
            index=models.Index(
                fields=["requires_manual_review"], name="tst_answer_review_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="testattemptanswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="uq_tst_answer_question"
            ),
        ),
    ]
