# Generated by Django 5.2.14 on 2026-06-09 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="testattempt",
            new_name="tst_attempt_user_idx",
            old_name="tst_attempt_test_user_idx",
        ),
        migrations.RenameIndex(
            model_name="testattempt",
            new_name="tst_attempt_conf_idx",
            old_name="tst_attempt_confirm_idx",
        ),
        migrations.RenameIndex(
            model_name="testattempt",
            new_name="tst_attempt_vis_idx",
            old_name="tst_attempt_visible_idx",
        ),
        migrations.RenameIndex(
            model_name="testlearnerresult",
            new_name="tst_result_user_idx",
            old_name="tst_result_test_user_idx",
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="auto_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="auto_grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="final_grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="is_confirmed_by_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="is_visible_to_guardian",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="is_visible_to_learner",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="requires_manual_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="teacher_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="teacher_grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="testattemptanswer",
            name="auto_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="testattemptanswer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="testattemptanswer",
            name="final_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="testattemptanswer",
            name="number_answer",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="testattemptanswer",
            name="requires_manual_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="testattemptanswer",
            name="teacher_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="testattemptanswer",
            name="teacher_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="testattemptanswer",
            name="text_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="testattemptanswer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="attempts_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="average_grade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="average_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="best_grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="best_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="confirmed_attempts_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="grade_source",
            field=models.CharField(
                choices=[
                    ("auto", "Автоматически рассчитана"),
                    ("teacher", "Подтверждена преподавателем"),
                    ("average", "Средняя по попыткам"),
                ],
                default="average",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="is_passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="is_visible_to_guardian",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="is_visible_to_learner",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="last_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="result_as_last_attempt",
                to="testing.testattempt",
            ),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активен"),
                    ("blocked", "Повторное прохождение заблокировано"),
                    ("archived", "Архивирован"),
                ],
                default="active",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="testlearnerresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
