# Generated by Django 5.2.14 on 2026-06-11 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_groupcurator_teacherorganization_and_more"),
        (
            "testing",
            "0002_rename_tst_attempt_test_user_idx_tst_attempt_user_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBankItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                ("explanation", models.TextField(blank=True, verbose_name="Пояснение")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Один вариант ответа"),
                            ("multiple_choice", "Несколько вариантов ответа"),
                            ("true_false", "Верно / неверно"),
                            ("short_text", "Короткий текстовый ответ"),
                            ("number", "Числовой ответ"),
                        ],
                        default="single_choice",
                        max_length=32,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "check_mode",
                    models.CharField(
                        choices=[
                            ("auto", "Автоматическая проверка"),
                            ("manual", "Ручная проверка"),
                            ("semi_auto", "Полуавтоматическая проверка"),
                        ],
                        default="auto",
                        max_length=32,
                        verbose_name="Режим проверки",
                    ),
                ),
                (
                    "expected_text_answer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Ожидаемый текстовый ответ",
                    ),
                ),
                (
                    "expected_number_answer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Ожидаемый числовой ответ",
                    ),
                ),
                (
                    "case_sensitive",
                    models.BooleanField(
                        default=False, verbose_name="Учитывать регистр"
                    ),
                ),
                ("score", models.PositiveIntegerField(default=1, verbose_name="Балл")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Лёгкий"),
                            ("medium", "Средний"),
                            ("hard", "Сложный"),
                        ],
                        default="medium",
                        max_length=32,
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "tags_data",
                    models.JSONField(blank=True, default=list, verbose_name="Теги"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Только автор"),
                            ("organization", "Организация"),
                            ("public", "Платформа"),
                        ],
                        default="private",
                        max_length=32,
                        verbose_name="Видимость",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликован"),
                            ("archived", "Архив"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата архивирования"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Шаблон вопроса",
                "verbose_name_plural": "Банк тестовых заданий",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="QuestionBankOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст варианта")),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильный ответ"),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Балл за вариант",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Пояснение к варианту"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Вариант шаблона вопроса",
                "verbose_name_plural": "Варианты шаблонов вопросов",
                "ordering": ("bank_item_id", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TestAttemptIntegrityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Итоговый риск, баллы"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Низкий риск"),
                            ("medium", "Средний риск"),
                            ("high", "Высокий риск"),
                        ],
                        default="low",
                        max_length=32,
                        verbose_name="Уровень риска",
                    ),
                ),
                (
                    "flags_data",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Признаки риска"
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата анализа"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Отчёт добросовестности попытки",
                "verbose_name_plural": "Отчёты добросовестности попыток",
                "ordering": ("-checked_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="testattempt",
            name="expired_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата истечения попытки"
            ),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время истечения попытки"
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Лёгкий"),
                    ("medium", "Средний"),
                    ("hard", "Сложный"),
                ],
                default="medium",
                max_length=32,
                verbose_name="Сложность",
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="is_reusable",
            field=models.BooleanField(
                default=False, verbose_name="Можно переиспользовать"
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="tags_data",
            field=models.JSONField(blank=True, default=list, verbose_name="Теги"),
        ),
        migrations.AddIndex(
            model_name="testattempt",
            index=models.Index(fields=["expires_at"], name="tst_attempt_expires_idx"),
        ),
        migrations.AddField(
            model_name="questionbankitem",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="question_bank_items",
                to="organizations.organization",
                verbose_name="Организация",
            ),
        ),
        migrations.AddField(
            model_name="questionbankitem",
            name="owner_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_question_bank_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель-владелец",
            ),
        ),
        migrations.AddField(
            model_name="questionbankitem",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="question_bank_items",
                to="organizations.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="source_bank_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_test_questions",
                to="testing.questionbankitem",
                verbose_name="Источник из банка заданий",
            ),
        ),
        migrations.AddIndex(
            model_name="testquestion",
            index=models.Index(
                fields=["source_bank_item"], name="tst_question_bank_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testquestion",
            index=models.Index(fields=["difficulty"], name="tst_question_diff_idx"),
        ),
        migrations.AddIndex(
            model_name="testquestion",
            index=models.Index(fields=["is_reusable"], name="tst_question_reuse_idx"),
        ),
        migrations.AddField(
            model_name="questionbankoption",
            name="bank_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="testing.questionbankitem",
                verbose_name="Шаблон вопроса",
            ),
        ),
        migrations.AddField(
            model_name="testattemptintegrityreport",
            name="attempt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrity_report",
                to="testing.testattempt",
                verbose_name="Попытка",
            ),
        ),
        migrations.AddIndex(
            model_name="questionbankitem",
            index=models.Index(fields=["status"], name="tst_bank_status_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbankitem",
            index=models.Index(fields=["visibility"], name="tst_bank_vis_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbankitem",
            index=models.Index(fields=["difficulty"], name="tst_bank_diff_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbankitem",
            index=models.Index(fields=["question_type"], name="tst_bank_type_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbankitem",
            index=models.Index(fields=["organization"], name="tst_bank_org_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbankitem",
            index=models.Index(fields=["subject"], name="tst_bank_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbankitem",
            index=models.Index(fields=["owner_teacher"], name="tst_bank_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbankitem",
            index=models.Index(fields=["is_active"], name="tst_bank_active_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbankoption",
            index=models.Index(fields=["bank_item"], name="tst_bank_opt_item_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbankoption",
            index=models.Index(fields=["is_correct"], name="tst_bank_opt_corr_idx"),
        ),
        migrations.AddIndex(
            model_name="questionbankoption",
            index=models.Index(fields=["is_active"], name="tst_bank_opt_act_idx"),
        ),
        migrations.AddConstraint(
            model_name="questionbankoption",
            constraint=models.UniqueConstraint(
                fields=("bank_item", "order"), name="uq_tst_bank_option_order"
            ),
        ),
        migrations.AddIndex(
            model_name="testattemptintegrityreport",
            index=models.Index(fields=["attempt"], name="tst_integrity_att_idx"),
        ),
        migrations.AddIndex(
            model_name="testattemptintegrityreport",
            index=models.Index(fields=["risk_level"], name="tst_integrity_risk_idx"),
        ),
        migrations.AddIndex(
            model_name="testattemptintegrityreport",
            index=models.Index(fields=["score"], name="tst_integrity_score_idx"),
        ),
        migrations.AddIndex(
            model_name="testattemptintegrityreport",
            index=models.Index(fields=["checked_at"], name="tst_integrity_date_idx"),
        ),
    ]
