# Generated by Django 5.2.14 on 2026-05-24 10:31

import apps.notifications.models.notification_mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Заголовок")),
                (
                    "message",
                    models.TextField(max_length=1200, verbose_name="Сообщение"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("daily_summary", "Ежедневная сводка"),
                            ("birthday", "День рождения"),
                            ("assignment_due_today", "Задание к сдаче сегодня"),
                            ("assignment_due_tomorrow", "Задание к сдаче завтра"),
                            ("assignment_due_soon", "Задание к сдаче скоро"),
                            ("assignment_overdue", "Просроченное задание"),
                            ("test_today", "Контрольная сегодня"),
                            ("test_tomorrow", "Контрольная завтра"),
                            ("exam_today", "Экзамен сегодня"),
                            ("exam_tomorrow", "Экзамен завтра"),
                            ("calendar_event_today", "Событие календаря сегодня"),
                            ("note_reminder", "Напоминание заметки"),
                            ("schedule_changed", "Изменение расписания"),
                            ("work_to_check", "Работы на проверку"),
                            ("moderation_request", "Заявка на модерацию"),
                            ("support_request", "Обращение в поддержку"),
                            ("security", "Безопасность"),
                            ("system", "Системное уведомление"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="Тип уведомления",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("daily_summary", "Ежедневная сводка"),
                            ("assignments", "Задания"),
                            ("tests", "Контрольные и экзамены"),
                            ("schedule", "Расписание"),
                            ("calendar", "Календарь"),
                            ("notes", "Заметки"),
                            ("birthday", "День рождения"),
                            ("education", "Образование"),
                            ("feedback", "Обратная связь"),
                            ("moderation", "Модерация"),
                            ("security", "Безопасность"),
                            ("system", "Система"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Информация"),
                            ("success", "Успешное событие"),
                            ("warning", "Предупреждение"),
                            ("danger", "Критичное уведомление"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=24,
                        verbose_name="Уровень важности",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Не прочитано"),
                            ("read", "Прочитано"),
                            ("completed", "Выполнено"),
                            ("archived", "В архиве"),
                        ],
                        db_index=True,
                        default="unread",
                        max_length=24,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "recipient_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin", "Администратор"),
                            ("teacher", "Преподаватель"),
                            ("learner", "Студент"),
                            ("guardian", "Родитель"),
                        ],
                        db_index=True,
                        default="",
                        max_length=32,
                        verbose_name="Роль получателя",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("user", "Пользователь"),
                            ("assignment", "Задание"),
                            ("test", "Контрольная"),
                            ("exam", "Экзамен"),
                            ("lesson", "Урок"),
                            ("course", "Курс"),
                            ("schedule", "Расписание"),
                            ("calendar_event", "Событие календаря"),
                            ("note", "Заметка"),
                            ("support_request", "Обращение"),
                            ("moderation_request", "Заявка на модерацию"),
                            ("security_event", "Событие безопасности"),
                            ("system", "Система"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=64,
                        verbose_name="Тип источника",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="ID источника",
                    ),
                ),
                (
                    "deduplication_key",
                    models.CharField(
                        db_index=True,
                        help_text="Ключ, который не позволяет создать одно и то же уведомление несколько раз за один период.",
                        max_length=255,
                        unique=True,
                        verbose_name="Ключ дедупликации",
                    ),
                ),
                (
                    "action_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Текст действия",
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Ссылка действия",
                    ),
                ),
                (
                    "delivery_channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список каналов доставки: in_app, email, vk, max.",
                        verbose_name="Каналы доставки",
                    ),
                ),
                (
                    "delivery_statuses",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Состояние доставки уведомления по каналам.",
                        verbose_name="Статусы доставки",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Технические данные для frontend, WebSocket и доставок.",
                        verbose_name="Дополнительные данные",
                    ),
                ),
                (
                    "event_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Дата события, к которому относится уведомление: дедлайн, напоминание, контрольная или событие календаря.",
                        null=True,
                        verbose_name="Дата события",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата прочтения"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата выполнения"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="После этой даты уведомление может быть удалено задачей очистки.",
                        null=True,
                        verbose_name="Дата удаления",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["status", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status", "-created_at"],
                        name="notif_user_status_created_idx",
                    ),
                    models.Index(
                        fields=["recipient", "category", "-created_at"],
                        name="notif_user_category_idx",
                    ),
                    models.Index(
                        fields=["recipient", "notification_type", "-created_at"],
                        name="notif_user_type_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_id"], name="notif_source_idx"
                    ),
                    models.Index(fields=["expires_at"], name="notif_expires_idx"),
                ],
            },
            bases=(
                apps.notifications.models.notification_mixins.NotificationLifecycleMixin,
                models.Model,
            ),
        ),
    ]
