from __future__ import annotations

COURSE_PLAN_MUTABLE_FIELDS = {
    "course",
    "course_id",
    "discipline_name",
    "discipline_code",
    "specialty_code",
    "specialty_name",
    "teacher_name_snapshot",
    "organization_name_snapshot",
    "academic_year_label",
    "semester_number",
    "total_hours",
    "semester_hours",
    "theory_hours",
    "practice_hours",
    "lab_hours",
    "self_study_hours",
    "consultation_hours",
    "commission_name",
    "protocol_number",
    "protocol_date",
    "approved_order_number",
    "approved_order_date",
    "status",
    "is_active",
    "notes",
}

COURSE_PLAN_IMPORT_MUTABLE_FIELDS = {
    "course_plan",
    "course_plan_id",
    "source_file",
    "original_filename",
    "file_hash",
    "status",
    "parser_version",
    "parsed_payload",
    "errors",
    "imported_by",
    "imported_by_id",
    "applied_at",
}
