# Generated by Django 5.2.14 on 2026-05-16 20:30

import apps.core.validators
import apps.users.managers.user_manager
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("learner", "Учащийся"),
                            ("guardian", "Родитель / законный представитель"),
                            ("teacher", "Преподаватель"),
                            ("curator", "Куратор группы"),
                            ("methodist", "Методист"),
                            ("organizer", "Педагог-организатор"),
                            ("mentor", "Педагог-наставник"),
                            ("department_head", "Заведующий отделением"),
                            ("director", "Директор"),
                            ("org_admin", "Администратор организации"),
                            ("superadmin", "Суперадминистратор"),
                        ],
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Код роли",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=150, verbose_name="Название роли"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_system",
                    models.BooleanField(default=True, verbose_name="Системная роль"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
                "db_table": "users_role",
                "ordering": ("sort_order", "label"),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата архивации"
                    ),
                ),
                (
                    "archive_reason",
                    models.TextField(blank=True, verbose_name="Причина архивации"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
                (
                    "delete_reason",
                    models.TextField(blank=True, verbose_name="Причина удаления"),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        validators=[apps.core.validators.validate_phone_number],
                        verbose_name="Телефон",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Отчество"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            apps.core.validators.validate_birth_date_not_future
                        ],
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_email", "Ожидает подтверждения email"),
                            ("pending_review", "Ожидает проверки"),
                            ("active", "Активен"),
                            ("rejected", "Отклонён"),
                            ("blocked", "Заблокирован"),
                            ("archived", "В архиве"),
                            ("scheduled_for_deletion", "Запланирован к удалению"),
                            ("anonymized", "Анонимизирован"),
                        ],
                        db_index=True,
                        default="pending_email",
                        max_length=32,
                        verbose_name="Статус аккаунта",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="Доступ в административную панель"
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False, verbose_name="Email подтверждён"
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата подтверждения email"
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(
                        default=False, verbose_name="Телефон подтверждён"
                    ),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата подтверждения телефона",
                    ),
                ),
                (
                    "is_login_allowed",
                    models.BooleanField(
                        default=True, verbose_name="Самостоятельный вход разрешён"
                    ),
                ),
                (
                    "login_available_from",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Самостоятельный вход доступен с",
                    ),
                ),
                (
                    "login_activation_requested_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата запроса самостоятельного входа",
                    ),
                ),
                (
                    "login_activated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата активации самостоятельного входа",
                    ),
                ),
                (
                    "scheduled_for_deletion_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата планируемого удаления"
                    ),
                ),
                (
                    "anonymized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата анонимизации"
                    ),
                ),
                (
                    "account_managed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Используется для аккаунтов детей младше 14 лет.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Аккаунтом управляет",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Архивировал",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Удалил",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "users_user",
                "ordering": ("last_name", "first_name", "email"),
            },
            managers=[
                ("objects", apps.users.managers.user_manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="GuardianLearner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("mother", "Мать"),
                            ("father", "Отец"),
                            ("guardian", "Опекун"),
                            ("representative", "Законный представитель"),
                            ("other", "Иное"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="Тип связи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("active", "Активна"),
                            ("rejected", "Отклонена"),
                            ("revoked", "Отозвана"),
                            ("archived", "В архиве"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="Статус связи",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Основной представитель"
                    ),
                ),
                (
                    "is_learner_consent_required",
                    models.BooleanField(
                        default=False, verbose_name="Требуется согласие учащегося"
                    ),
                ),
                (
                    "curator_code_verified_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата подтверждения кода куратора",
                    ),
                ),
                (
                    "learner_code_verified_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата подтверждения кода учащегося",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата подтверждения"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_guardian_learner_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подтвердил",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_learner_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Родитель",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_guardian_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учащийся",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_guardian_learner_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор запроса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь родителя и учащегося",
                "verbose_name_plural": "Связи родителей и учащихся",
                "db_table": "users_guardian_learner",
                "ordering": ("-is_primary", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="GuardianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending_review", "Ожидает проверки"),
                            ("verified", "Подтверждён"),
                            ("rejected", "Отклонён"),
                            ("archived", "В архиве"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                        verbose_name="Статус профиля",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Род деятельности"
                    ),
                ),
                (
                    "work_place",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Место работы"
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        validators=[apps.core.validators.validate_phone_number],
                        verbose_name="Экстренный телефон для связи",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Служебные заметки"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль родителя",
                "verbose_name_plural": "Профили родителей",
                "db_table": "users_guardian_profile",
            },
        ),
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "code_hash",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="Хеш кода",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("teacher_registration", "Регистрация преподавателя"),
                            ("guardian_link_curator", "Связь родителя: код куратора"),
                            ("guardian_link_learner", "Связь родителя: код учащегося"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="Назначение кода",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Дата истечения")),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Максимальное количество использований"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество использований"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последнего использования",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invite_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invite_codes",
                        to="organizations.department",
                        verbose_name="Отделение",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invite_codes",
                        to="organizations.studygroup",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_codes",
                        to="organizations.organization",
                        verbose_name="Образовательная организация",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_invite_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Целевой пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Код приглашения",
                "verbose_name_plural": "Коды приглашения",
                "db_table": "users_invite_code",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LearnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "learner_code",
                    models.CharField(
                        blank=True,
                        help_text="Например: ИСП-22-01 или иной код внутри организации.",
                        max_length=64,
                        verbose_name="Внутренний код учащегося",
                    ),
                ),
                (
                    "admission_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год поступления"
                    ),
                ),
                (
                    "admission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата зачисления"
                    ),
                ),
                (
                    "graduation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата выпуска"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending_review", "Ожидает проверки"),
                            ("verified", "Подтверждён"),
                            ("rejected", "Отклонён"),
                            ("archived", "В архиве"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                        verbose_name="Статус профиля",
                    ),
                ),
                (
                    "is_minor",
                    models.BooleanField(
                        default=False, verbose_name="Учащийся младше 14 лет"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Служебные заметки"
                    ),
                ),
                (
                    "verification_comment",
                    models.TextField(blank=True, verbose_name="Комментарий проверки"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата подтверждения"
                    ),
                ),
                (
                    "created_by_guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_learner_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создан родителем",
                    ),
                ),
                (
                    "curator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curated_learner_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Куратор",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learner_profiles",
                        to="organizations.department",
                        verbose_name="Отделение",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learner_profiles",
                        to="organizations.studygroup",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learner_profiles",
                        to="organizations.organization",
                        verbose_name="Образовательная организация",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_learner_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подтвердил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль учащегося",
                "verbose_name_plural": "Профили учащихся",
                "db_table": "users_learner_profile",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Мужской"),
                            ("female", "Женский"),
                            ("not_specified", "Не указан"),
                        ],
                        default="not_specified",
                        max_length=32,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/avatars/%Y/%m/",
                        validators=[apps.core.validators.validate_image_extension],
                        verbose_name="Аватар",
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="О себе")),
                (
                    "city",
                    models.CharField(blank=True, max_length=150, verbose_name="Город"),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        default="Europe/Moscow",
                        max_length=150,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "social_link_max",
                    models.URLField(
                        blank=True, default="", verbose_name="Ссылка на профиль в MAX"
                    ),
                ),
                (
                    "social_link_vk",
                    models.URLField(
                        blank=True,
                        default="",
                        verbose_name="Ссылка на профиль во ВКонтакте",
                    ),
                ),
                (
                    "avatar_moderation_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Не отправлено"),
                            ("pending", "Ожидает модерации"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="not_submitted",
                        max_length=32,
                        verbose_name="Статус модерации аватара",
                    ),
                ),
                (
                    "profile_moderation_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Не отправлено"),
                            ("pending", "Ожидает модерации"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="not_submitted",
                        max_length=32,
                        verbose_name="Статус модерации профиля",
                    ),
                ),
                (
                    "moderation_comment",
                    models.TextField(blank=True, verbose_name="Комментарий модератора"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
                "db_table": "users_profile",
                "ordering": ("user__last_name", "user__first_name"),
            },
        ),
        migrations.CreateModel(
            name="RegistrationAttemptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "email_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="Хеш email",
                    ),
                ),
                (
                    "phone_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        verbose_name="Хеш телефона",
                    ),
                ),
                (
                    "role_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Код роли",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Успешно"),
                            ("failed", "Ошибка"),
                            ("blocked", "Заблокировано лимитом"),
                        ],
                        db_index=True,
                        default="failed",
                        max_length=32,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Причина ошибки"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка регистрации",
                "verbose_name_plural": "Попытки регистрации",
                "db_table": "users_registration_attempt_log",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["email_hash"], name="users_reg_email_hash_idx"
                    ),
                    models.Index(
                        fields=["phone_hash"], name="users_reg_phone_hash_idx"
                    ),
                    models.Index(fields=["ip_address"], name="users_reg_ip_idx"),
                    models.Index(fields=["status"], name="users_reg_status_idx"),
                    models.Index(fields=["created_at"], name="users_reg_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Должность"
                    ),
                ),
                (
                    "public_title",
                    models.CharField(
                        blank=True,
                        help_text='Например: "Преподаватель математики".',
                        max_length=255,
                        verbose_name="Публичный заголовок",
                    ),
                ),
                (
                    "short_bio",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Краткое описание"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Описание")),
                ("education", models.TextField(blank=True, verbose_name="Образование")),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Стаж, лет"
                    ),
                ),
                (
                    "achievements",
                    models.TextField(blank=True, verbose_name="Достижения и награды"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/teachers/covers/%Y/%m/",
                        validators=[apps.core.validators.validate_image_extension],
                        verbose_name="Обложка карточки преподавателя",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Публичный профиль"),
                ),
                (
                    "show_on_teachers_page",
                    models.BooleanField(
                        default=True,
                        verbose_name="Показывать на странице преподавателей",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending_review", "Ожидает проверки"),
                            ("verified", "Подтверждён"),
                            ("rejected", "Отклонён"),
                            ("archived", "В архиве"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                        verbose_name="Статус профиля",
                    ),
                ),
                (
                    "code_verified_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата подтверждения регистрационного кода",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата подтверждения"
                    ),
                ),
                (
                    "verification_comment",
                    models.TextField(blank=True, verbose_name="Комментарий проверки"),
                ),
                (
                    "hired_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала работы"
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата увольнения"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_profiles",
                        to="organizations.department",
                        verbose_name="Отделение",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teacher_profiles",
                        to="organizations.organization",
                        verbose_name="Образовательная организация",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_teacher_profiles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подтвердил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль преподавателя",
                "verbose_name_plural": "Профили преподавателей",
                "db_table": "users_teacher_profile",
            },
        ),
        migrations.CreateModel(
            name="UserAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "Пользователь"),
                            ("system", "Система"),
                            ("admin", "Администратор"),
                        ],
                        default="user",
                        max_length=32,
                        verbose_name="Тип инициатора",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_registered", "Пользователь зарегистрирован"),
                            ("email_verified", "Email подтверждён"),
                            (
                                "phone_verification_requested",
                                "Запрошено подтверждение телефона",
                            ),
                            ("phone_verified", "Телефон подтверждён"),
                            ("role_assigned", "Роль назначена"),
                            ("role_approved", "Роль подтверждена"),
                            ("role_rejected", "Роль отклонена"),
                            ("role_revoked", "Роль отозвана"),
                            ("join_request_created", "Заявка создана"),
                            ("join_request_approved", "Заявка подтверждена"),
                            ("join_request_rejected", "Заявка отклонена"),
                            ("join_request_cancelled", "Заявка отменена"),
                            ("join_request_expired", "Заявка истекла"),
                            ("invite_code_created", "Код приглашения создан"),
                            ("invite_code_used", "Код приглашения использован"),
                            ("invite_code_expired", "Код приглашения истёк"),
                            ("invite_code_disabled", "Код приглашения отключён"),
                            ("profile_created", "Профиль создан"),
                            ("profile_updated", "Профиль обновлён"),
                            ("profile_verified", "Профиль подтверждён"),
                            ("profile_rejected", "Профиль отклонён"),
                            ("avatar_submitted", "Аватар отправлен на модерацию"),
                            ("avatar_approved", "Аватар одобрен"),
                            ("avatar_rejected", "Аватар отклонён"),
                            (
                                "guardian_link_created",
                                "Связь родителя и учащегося создана",
                            ),
                            (
                                "guardian_link_approved",
                                "Связь родителя и учащегося подтверждена",
                            ),
                            (
                                "guardian_link_rejected",
                                "Связь родителя и учащегося отклонена",
                            ),
                            (
                                "guardian_link_revoked",
                                "Связь родителя и учащегося отозвана",
                            ),
                            ("user_blocked", "Пользователь заблокирован"),
                            ("user_unblocked", "Пользователь разблокирован"),
                            ("user_archived", "Пользователь архивирован"),
                            ("user_restored", "Пользователь восстановлен"),
                            (
                                "user_scheduled_for_deletion",
                                "Пользователь запланирован к удалению",
                            ),
                            ("user_anonymized", "Пользователь анонимизирован"),
                            ("login_success", "Успешный вход"),
                            ("login_failed", "Неудачная попытка входа"),
                            ("logout", "Выход из системы"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="Действие",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_user_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Целевой пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись аудита пользователя",
                "verbose_name_plural": "Аудит пользователей",
                "db_table": "users_audit_log",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UserJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("teacher_to_organization", "Преподаватель в организацию"),
                            ("learner_to_group", "Учащийся в группу"),
                            ("guardian_to_learner", "Родитель к учащемуся"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="Тип заявки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает проверки"),
                            ("approved", "Подтверждена"),
                            ("rejected", "Отклонена"),
                            ("cancelled", "Отменена"),
                            ("expired", "Истекла"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Сообщение пользователя"),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, verbose_name="Комментарий проверки"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Если пусто, заявка может ожидать проверки без автоистечения.",
                        null=True,
                        verbose_name="Дата истечения заявки",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_join_requests",
                        to="organizations.department",
                        verbose_name="Отделение",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_join_requests",
                        to="organizations.studygroup",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_join_requests",
                        to="organizations.organization",
                        verbose_name="Образовательная организация",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_join_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверил",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Используется для связи родителя с учащимся.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_join_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Целевой пользователь",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка пользователя",
                "verbose_name_plural": "Заявки пользователей",
                "db_table": "users_join_request",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("active", "Активна"),
                            ("rejected", "Отклонена"),
                            ("revoked", "Отозвана"),
                            ("archived", "В архиве"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                        verbose_name="Статус роли",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата назначения",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отзыва"
                    ),
                ),
                (
                    "revoke_reason",
                    models.TextField(blank=True, verbose_name="Причина отзыва"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначил",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_roles",
                        to="organizations.department",
                        verbose_name="Отделение",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_roles",
                        to="organizations.studygroup",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="organizations.organization",
                        verbose_name="Образовательная организация",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отозвал",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_roles",
                        to="users.role",
                        verbose_name="Роль",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль пользователя",
                "verbose_name_plural": "Роли пользователей",
                "db_table": "users_user_role",
                "ordering": ("user", "role"),
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "language",
                    models.CharField(
                        default="ru", max_length=16, verbose_name="Язык интерфейса"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow",
                        max_length=150,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "active_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("learner", "Учащийся"),
                            ("guardian", "Родитель / законный представитель"),
                            ("teacher", "Преподаватель"),
                            ("curator", "Куратор группы"),
                            ("methodist", "Методист"),
                            ("organizer", "Педагог-организатор"),
                            ("mentor", "Педагог-наставник"),
                            ("department_head", "Заведующий отделением"),
                            ("director", "Директор"),
                            ("org_admin", "Администратор организации"),
                            ("superadmin", "Суперадминистратор"),
                        ],
                        max_length=64,
                        verbose_name="Активная роль",
                    ),
                ),
                (
                    "interface_theme",
                    models.CharField(
                        choices=[
                            ("default", "По умолчанию"),
                            ("junior", "Младшие классы"),
                            ("middle", "Средние классы"),
                            ("senior", "Старшие классы"),
                            ("college", "Колледж"),
                            ("university", "Университет"),
                            ("teacher", "Преподаватель"),
                            ("guardian", "Родитель"),
                            ("admin", "Администратор"),
                        ],
                        default="default",
                        max_length=32,
                        verbose_name="Тема интерфейса",
                    ),
                ),
                (
                    "compact_mode",
                    models.BooleanField(default=False, verbose_name="Компактный режим"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки пользователя",
                "verbose_name_plural": "Настройки пользователей",
                "db_table": "users_user_settings",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="users_user_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["status"], name="users_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="guardianlearner",
            index=models.Index(
                fields=["guardian", "status"], name="users_gl_guardian_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardianlearner",
            index=models.Index(
                fields=["learner", "status"], name="users_gl_learner_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianlearner",
            constraint=models.UniqueConstraint(
                fields=("guardian", "learner"), name="users_guardian_learner_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianlearner",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("learner",),
                name="users_guardian_learner_one_primary",
            ),
        ),
        migrations.AddIndex(
            model_name="invitecode",
            index=models.Index(fields=["code_hash"], name="users_invite_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="invitecode",
            index=models.Index(
                fields=["purpose", "is_active"], name="users_invite_purpose_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitecode",
            index=models.Index(fields=["organization"], name="users_invite_org_idx"),
        ),
        migrations.AddIndex(
            model_name="invitecode",
            index=models.Index(fields=["expires_at"], name="users_invite_expires_idx"),
        ),
        migrations.AddIndex(
            model_name="learnerprofile",
            index=models.Index(
                fields=["organization", "status"], name="users_lp_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learnerprofile",
            index=models.Index(
                fields=["department", "status"], name="users_lp_dept_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learnerprofile",
            index=models.Index(
                fields=["group", "status"], name="users_lp_group_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learnerprofile",
            index=models.Index(
                fields=["curator", "status"], name="users_lp_cur_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["organization", "status"], name="users_tp_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["department", "status"], name="users_tp_dept_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["show_on_teachers_page"], name="users_tp_show_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userauditlog",
            index=models.Index(fields=["action"], name="users_audit_action_idx"),
        ),
        migrations.AddIndex(
            model_name="userauditlog",
            index=models.Index(fields=["target_user"], name="users_audit_target_idx"),
        ),
        migrations.AddIndex(
            model_name="userauditlog",
            index=models.Index(fields=["created_at"], name="users_audit_created_idx"),
        ),
        migrations.AddIndex(
            model_name="userjoinrequest",
            index=models.Index(
                fields=["request_type", "status"], name="users_join_type_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userjoinrequest",
            index=models.Index(
                fields=["user", "status"], name="users_join_user_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userjoinrequest",
            index=models.Index(
                fields=["organization", "status"], name="users_join_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userjoinrequest",
            index=models.Index(
                fields=["group", "status"], name="users_join_group_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "status"], name="users_ur_user_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["role", "status"], name="users_ur_role_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["organization"], name="users_ur_org_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["department"], name="users_ur_dept_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["group"], name="users_ur_group_idx"),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("department__isnull", True),
                    ("group__isnull", True),
                    ("organization__isnull", True),
                ),
                fields=("user", "role"),
                name="users_user_role_unique_platform",
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("department__isnull", True),
                    ("group__isnull", True),
                    ("organization__isnull", False),
                ),
                fields=("user", "role", "organization"),
                name="users_user_role_unique_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("department__isnull", False),
                    ("group__isnull", True),
                    ("organization__isnull", False),
                ),
                fields=("user", "role", "organization", "department"),
                name="users_user_role_unique_department",
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("group__isnull", False), ("organization__isnull", False)
                ),
                fields=("user", "role", "organization", "group"),
                name="users_user_role_unique_group",
            ),
        ),
    ]
