# Generated by Django 5.2.14 on 2026-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_seed_system_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("learner", "Учащийся"),
                    ("guardian", "Родитель / законный представитель"),
                    ("teacher", "Преподаватель"),
                    ("curator", "Куратор группы"),
                    ("methodist", "Методист"),
                    ("organizer", "Педагог-организатор"),
                    ("mentor", "Педагог-наставник"),
                    ("department_head", "Заведующий отделением"),
                    ("director", "Директор"),
                    ("org_admin", "Администратор организации"),
                    ("superadmin", "Суперадминистратор"),
                    ("platform_admin", "Администратор платформы"),
                    ("moderator", "Модератор"),
                    ("support", "Техническая поддержка"),
                ],
                db_index=True,
                max_length=64,
                unique=True,
                verbose_name="Код роли",
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="active_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("learner", "Учащийся"),
                    ("guardian", "Родитель / законный представитель"),
                    ("teacher", "Преподаватель"),
                    ("curator", "Куратор группы"),
                    ("methodist", "Методист"),
                    ("organizer", "Педагог-организатор"),
                    ("mentor", "Педагог-наставник"),
                    ("department_head", "Заведующий отделением"),
                    ("director", "Директор"),
                    ("org_admin", "Администратор организации"),
                    ("superadmin", "Суперадминистратор"),
                    ("platform_admin", "Администратор платформы"),
                    ("moderator", "Модератор"),
                    ("support", "Техническая поддержка"),
                ],
                max_length=64,
                verbose_name="Активная роль",
            ),
        ),
    ]
