# Generated by Django 5.2.14 on 2026-05-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_role_code_alter_usersettings_active_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_notifications",
            field=models.BooleanField(default=True, verbose_name="Email-уведомления"),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[
                    ("email", "Электронная почта"),
                    ("phone", "Телефон"),
                    ("telegram", "Telegram"),
                    ("vk", "ВКонтакте"),
                    ("max", "MAX"),
                ],
                default="email",
                max_length=32,
                verbose_name="Предпочтительный способ связи",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="push_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Внутрисистемные уведомления"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_email",
            field=models.BooleanField(
                default=True, verbose_name="Показывать email в профиле"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_phone",
            field=models.BooleanField(
                default=False, verbose_name="Показывать телефон в профиле"
            ),
        ),
    ]
