# Generated by Django 5.2.14 on 2026-05-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_email_notifications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[
                    ("email", "Электронная почта"),
                    ("phone", "Телефон"),
                    ("vk", "ВКонтакте"),
                    ("max", "MAX"),
                ],
                default="email",
                max_length=32,
                verbose_name="Предпочтительный способ связи",
            ),
        ),
    ]
