# Generated by Django 5.2.14 on 2026-05-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_backup_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="appearance_settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Настройки внешнего вида"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="notification_settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Настройки уведомлений"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="privacy_settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Настройки приватности"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="role_settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Ролевые настройки интерфейса"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="security_settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Настройки безопасности"
            ),
        ),
    ]
