# Generated by Django 5.2.14 on 2026-05-19 13:09

import apps.feedback.models.feedback_attachment
import apps.feedback.validators.feedback_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("question", "Вопрос"),
                            ("partnership", "Сотрудничество"),
                            ("organization_connection", "Подключение организации"),
                            ("technical_support", "Техническая поддержка"),
                            ("bug", "Ошибка"),
                            ("other", "Другое"),
                        ],
                        db_index=True,
                        default="question",
                        max_length=64,
                        verbose_name="Тема обращения",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("contacts_page", "Страница контактов"),
                            ("error_modal", "Модальное окно ошибки"),
                            ("system", "Система"),
                        ],
                        db_index=True,
                        default="contacts_page",
                        max_length=64,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новое"),
                            ("in_progress", "В работе"),
                            ("answered", "Ответ отправлен"),
                            ("closed", "Закрыто"),
                            ("spam", "Спам"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=64,
                        verbose_name="Статус",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Организация"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Тема письма"
                    ),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "is_personal_data_consent",
                    models.BooleanField(
                        default=False,
                        verbose_name="Согласие на обработку персональных данных",
                    ),
                ),
                ("page_url", models.URLField(blank=True, verbose_name="URL страницы")),
                (
                    "frontend_route",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Frontend route"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Код ошибки"
                    ),
                ),
                (
                    "error_details",
                    models.TextField(
                        blank=True, verbose_name="Технические детали ошибки"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "admin_notification_sent",
                    models.BooleanField(
                        default=False,
                        verbose_name="Уведомление администратору отправлено",
                    ),
                ),
                (
                    "admin_notification_error",
                    models.TextField(
                        blank=True, verbose_name="Ошибка отправки уведомления"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
                "db_table": "feedback_request",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="FeedbackAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.feedback.models.feedback_attachment.feedback_attachment_upload_to,
                        validators=[
                            apps.feedback.validators.feedback_validators.validate_feedback_attachment
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Оригинальное имя файла",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="Размер файла"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Изображение"),
                            ("pdf", "PDF"),
                            ("document", "Документ"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=32,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "feedback_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="feedback.feedbackrequest",
                        verbose_name="Обращение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение обращения",
                "verbose_name_plural": "Вложения обращений",
                "db_table": "feedback_attachment",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="feedbackrequest",
            index=models.Index(
                fields=["status", "created_at"], name="fb_req_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackrequest",
            index=models.Index(fields=["topic", "created_at"], name="fb_req_topic_idx"),
        ),
        migrations.AddIndex(
            model_name="feedbackrequest",
            index=models.Index(
                fields=["source", "created_at"], name="fb_req_source_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackrequest",
            index=models.Index(fields=["email", "created_at"], name="fb_req_email_idx"),
        ),
        migrations.AddIndex(
            model_name="feedbackattachment",
            index=models.Index(
                fields=["feedback_request", "created_at"], name="fb_attach_req_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedbackattachment",
            index=models.Index(
                fields=["kind", "created_at"], name="fb_attach_kind_idx"
            ),
        ),
    ]
