# Generated by Django 5.2.14 on 2026-06-07 17:22

import uuid

import apps.materials.validators.material_validators
import apps.materials.validators.material_version_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_groupcurator_teacherorganization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        max_length=120,
                        validators=[
                            apps.materials.validators.material_validators.validate_material_slug
                        ],
                        verbose_name="Slug",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_categories",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="materials.materialcategory",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория материала",
                "verbose_name_plural": "Категории материалов",
                "db_table": "materials_category",
                "ordering": ("organization", "parent", "name"),
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        max_length=120,
                        unique=True,
                        validators=[
                            apps.materials.validators.material_validators.validate_material_slug
                        ],
                        verbose_name="Slug",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Краткое описание"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("file", "Файл"),
                            ("link", "Ссылка"),
                            ("text", "Текст"),
                            ("video", "Видео"),
                            ("image", "Изображение"),
                            ("presentation", "Презентация"),
                            ("document", "Документ"),
                            ("spreadsheet", "Таблица"),
                            ("archive", "Архив"),
                            ("code", "Код"),
                            ("embed", "Встраиваемый материал"),
                            ("other", "Другое"),
                        ],
                        default="file",
                        max_length=32,
                        verbose_name="Тип материала",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликован"),
                            ("archived", "Архивирован"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Приватный"),
                            ("organization", "Внутри организации"),
                            ("assigned_only", "Только назначенным"),
                            ("public", "Публичный"),
                        ],
                        default="private",
                        max_length=32,
                        verbose_name="Видимость",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Создан вручную"),
                            ("upload", "Загружен"),
                            ("import", "Импортирован"),
                            ("external", "Внешний источник"),
                            ("course", "Создан из курса"),
                        ],
                        default="manual",
                        max_length=32,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            apps.materials.validators.material_validators.validate_material_tags
                        ],
                        verbose_name="Теги",
                    ),
                ),
                (
                    "preview_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="materials/previews/",
                        verbose_name="Изображение предпросмотра",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата архивации"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materials",
                        to="organizations.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="materials.materialcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный материал",
                "verbose_name_plural": "Учебные материалы",
                "db_table": "materials_material",
                "ordering": ("organization", "category", "-updated_at", "title"),
            },
        ),
        migrations.CreateModel(
            name="MaterialUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Просмотр"),
                            ("download", "Скачивание"),
                            ("open_link", "Открытие ссылки"),
                            ("attach", "Прикрепление"),
                            ("detach", "Открепление"),
                            ("update", "Обновление"),
                            ("create_version", "Создание версии"),
                            ("publish", "Публикация"),
                            ("archive", "Архивация"),
                        ],
                        max_length=32,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("library", "Библиотека"),
                            ("course", "Курс"),
                            ("lesson", "Урок"),
                            ("assignment", "Задание"),
                            ("profile", "Профиль"),
                            ("admin", "Админка"),
                            ("other", "Другое"),
                        ],
                        default="library",
                        max_length=32,
                        verbose_name="Контекст",
                    ),
                ),
                (
                    "context_object_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="ID объекта контекста"
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="IP-адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="User-Agent"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Дополнительные данные"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата события"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="materials.material",
                        verbose_name="Материал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал использования материала",
                "verbose_name_plural": "Журнал использования материалов",
                "db_table": "materials_usage_log",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="MaterialVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            apps.materials.validators.material_version_validators.validate_material_version_number
                        ],
                        verbose_name="Номер версии",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("current", "Текущая"),
                            ("archived", "Архивная"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="Статус версии",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="materials/files/",
                        validators=[
                            apps.materials.validators.material_version_validators.validate_material_file_size
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="Внешняя ссылка"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, verbose_name="Текстовое содержимое"),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Исходное имя файла"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Размер файла, байт"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Контрольная сумма"
                    ),
                ),
                (
                    "change_log",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Описание изменений"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Текущая версия"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_material_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем создана версия",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="materials.material",
                        verbose_name="Материал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия материала",
                "verbose_name_plural": "Версии материалов",
                "db_table": "materials_version",
                "ordering": ("material", "-version_number", "-created_at"),
            },
        ),
        migrations.AddField(
            model_name="material",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="materials.materialversion",
                verbose_name="Текущая версия",
            ),
        ),
        migrations.AddIndex(
            model_name="materialcategory",
            index=models.Index(fields=["organization"], name="mat_category_org_idx"),
        ),
        migrations.AddIndex(
            model_name="materialcategory",
            index=models.Index(fields=["parent"], name="mat_category_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="materialcategory",
            index=models.Index(fields=["slug"], name="mat_category_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="materialcategory",
            index=models.Index(fields=["is_active"], name="mat_category_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="materialcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("organization", "slug"),
                name="mat_cat_unique_org_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", True)),
                fields=("slug",),
                name="mat_cat_unique_global_slug",
            ),
        ),
        migrations.AddIndex(
            model_name="materialusagelog",
            index=models.Index(fields=["material"], name="mat_usage_material_idx"),
        ),
        migrations.AddIndex(
            model_name="materialusagelog",
            index=models.Index(fields=["user"], name="mat_usage_user_idx"),
        ),
        migrations.AddIndex(
            model_name="materialusagelog",
            index=models.Index(fields=["action"], name="mat_usage_action_idx"),
        ),
        migrations.AddIndex(
            model_name="materialusagelog",
            index=models.Index(fields=["context"], name="mat_usage_context_idx"),
        ),
        migrations.AddIndex(
            model_name="materialusagelog",
            index=models.Index(fields=["created_at"], name="mat_usage_created_idx"),
        ),
        migrations.AddIndex(
            model_name="materialversion",
            index=models.Index(fields=["material"], name="mat_version_material_idx"),
        ),
        migrations.AddIndex(
            model_name="materialversion",
            index=models.Index(fields=["status"], name="mat_version_status_idx"),
        ),
        migrations.AddIndex(
            model_name="materialversion",
            index=models.Index(fields=["is_current"], name="mat_version_current_idx"),
        ),
        migrations.AddIndex(
            model_name="materialversion",
            index=models.Index(fields=["created_by"], name="mat_version_creator_idx"),
        ),
        migrations.AddConstraint(
            model_name="materialversion",
            constraint=models.UniqueConstraint(
                fields=("material", "version_number"), name="mat_ver_unique_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("material",),
                name="mat_ver_unique_current",
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["slug"], name="mat_material_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["material_type"], name="mat_material_type_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["status"], name="mat_material_status_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["visibility"], name="mat_material_vis_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["source"], name="mat_material_source_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["organization"], name="mat_material_org_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["subject"], name="mat_material_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["category"], name="mat_material_category_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["owner"], name="mat_material_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(fields=["is_active"], name="mat_material_active_idx"),
        ),
    ]
