# Generated by Django 5.2.14 on 2026-06-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ("organization_id", "category_id", "-updated_at", "title"),
                "verbose_name": "Учебный материал",
                "verbose_name_plural": "Учебные материалы",
            },
        ),
        migrations.AlterModelOptions(
            name="materialcategory",
            options={
                "ordering": ("organization_id", "parent_id", "name"),
                "verbose_name": "Категория материала",
                "verbose_name_plural": "Категории материалов",
            },
        ),
        migrations.AlterModelOptions(
            name="materialversion",
            options={
                "ordering": ("material_id", "-version_number", "-created_at"),
                "verbose_name": "Версия материала",
                "verbose_name_plural": "Версии материалов",
            },
        ),
    ]
