from __future__ import annotations

PERIOD_TYPE_YEAR = "year"
PERIOD_TYPE_SEMESTER = "semester"
PERIOD_TYPE_TRIMESTER = "trimester"
PERIOD_TYPE_QUARTER = "quarter"
PERIOD_TYPE_MODULE = "module"
PERIOD_TYPE_OTHER = "other"

CURRICULUM_STATUS_DRAFT = "draft"
CURRICULUM_STATUS_ACTIVE = "active"
CURRICULUM_STATUS_ARCHIVED = "archived"

ASSESSMENT_TYPE_NONE = "none"
ASSESSMENT_TYPE_PASS_FAIL = "pass_fail"
ASSESSMENT_TYPE_CREDIT = "credit"
ASSESSMENT_TYPE_EXAM = "exam"
ASSESSMENT_TYPE_TEST = "test"
ASSESSMENT_TYPE_PROJECT = "project"
ASSESSMENT_TYPE_OTHER = "other"

TEACHER_ASSIGNMENT_ROLE_PRIMARY = "primary"
TEACHER_ASSIGNMENT_ROLE_ASSISTANT = "assistant"
TEACHER_ASSIGNMENT_ROLE_SUBSTITUTE = "substitute"
TEACHER_ASSIGNMENT_ROLE_OTHER = "other"

ENROLLMENT_STATUS_ACTIVE = "active"
ENROLLMENT_STATUS_TRANSFERRED = "transferred"
ENROLLMENT_STATUS_SUSPENDED = "suspended"
ENROLLMENT_STATUS_GRADUATED = "graduated"
ENROLLMENT_STATUS_EXPELLED = "expelled"
ENROLLMENT_STATUS_ARCHIVED = "archived"

FINISHED_ENROLLMENT_STATUS_CODES = frozenset(
    {
        ENROLLMENT_STATUS_TRANSFERRED,
        ENROLLMENT_STATUS_GRADUATED,
        ENROLLMENT_STATUS_EXPELLED,
        ENROLLMENT_STATUS_ARCHIVED,
    }
)

ACTIVE_STUDY_GROUP_STATUS_CODE = "active"
