from __future__ import annotations

ACADEMIC_YEAR_NAME_MAX_LENGTH = 32

EDUCATION_CODE_MAX_LENGTH = 64
EDUCATION_NAME_MAX_LENGTH = 255
EDUCATION_STATUS_MAX_LENGTH = 32
EDUCATION_TYPE_MAX_LENGTH = 32
EDUCATION_ROLE_MAX_LENGTH = 32

MIN_STUDY_YEAR = 1900
MAX_STUDY_YEAR = 2100

DEFAULT_SEQUENCE = 1
DEFAULT_HOURS = 0
