from __future__ import annotations

COURSE_MUTABLE_FIELDS = {
    "code",
    "slug",
    "title",
    "subtitle",
    "description",
    "course_type",
    "origin",
    "status",
    "visibility",
    "level",
    "language",
    "owner_teacher",
    "owner_teacher_id",
    "organization",
    "organization_id",
    "subject",
    "subject_id",
    "academic_year",
    "academic_year_id",
    "period",
    "period_id",
    "cover_image",
    "is_template",
    "is_active",
    "allow_self_enrollment",
    "enrollment_code",
    "starts_at",
    "ends_at",
}
