export type {
    DashboardRole,
    DashboardTone,
} from "@/components/dashboard/types/dashboard-common.types";
export type {
    DashboardBrand,
    DashboardFloatingPanelConfig,
    DashboardNavigationItem,
    DashboardSearchConfig,
    DashboardShellConfig,
    DashboardSidebarExtraAction,
    DashboardSidebarExtraCard,
    DashboardTopbarLabels,
    DashboardTopbarUser,
    DashboardUserProfile,
} from "@/components/dashboard/types/dashboard-shell.types";
export type {
    DashboardCalendarContent,
    DashboardCalendarDay,
    DashboardCalendarDayEvent,
    DashboardCalendarEventThemeOption,
    DashboardCalendarEventType,
    DashboardCalendarLegendItem,
    DashboardCreateItemKind,
    DashboardCreateItemModalContent,
    DashboardCreateItemModalCopy,
    DashboardNoteItem,
    DashboardNotesContent,
    DashboardNotificationItem,
    DashboardNotificationsContent,
    DashboardPageScaffoldModel,
    DashboardProfileAction,
    DashboardProfilePanelContent,
} from "@/components/dashboard/types/dashboard-panels.types";
export type {
    DashboardAction,
    DashboardAiCardContent,
    DashboardCardSectionContent,
    DashboardCourseCardContent,
    DashboardCourseMetaItem,
    DashboardDayCardContent,
    DashboardDayStat,
    DashboardHeroAction,
    DashboardHeroBadge,
    DashboardHeroContent,
    DashboardHeroSectionContent,
    DashboardIntroBadge,
    DashboardIntroContent,
    DashboardListItem,
    DashboardMetricItem,
    DashboardMiniPlanItem,
    DashboardStatsCardContent,
    DashboardTimelineContent,
    DashboardTimelineItem,
} from "@/components/dashboard/types/dashboard-content.types";
export type {
    DashboardItemCreatePayload,
    DashboardItemDto,
} from "@/components/dashboard/types/dashboard-items.types";
