"""
Селекторы приложения users.

Selectors отвечают только за чтение данных и подготовку QuerySet.

Важно:
    Селекторы не должны изменять данные.
    Любые действия, которые меняют состояние системы, должны находиться
    в `users/services/`.
"""

from apps.users.selectors.audit_selectors import (
    get_audit_logs_by_action,
    get_audit_logs_by_actor,
    get_audit_logs_for_user,
    get_registration_attempts_by_email_hash,
    get_registration_attempts_by_ip,
    get_registration_attempts_by_phone_hash,
    get_registration_attempts_queryset,
    get_user_audit_logs_queryset,
)
from apps.users.selectors.current_profile_selectors import (
    get_active_role_code_for_user,
    get_current_role_profile,
    get_or_create_profile_for_user,
    get_role_label,
)
from apps.users.selectors.guardian_selectors import (
    get_active_guardian_learner_links_queryset,
    get_active_guardian_link,
    get_guardian_learner_links_queryset,
    get_guardian_link,
    get_guardian_profile_by_user,
    get_guardian_profiles_queryset,
    get_guardians_for_learner,
    get_learners_for_guardian,
    get_primary_guardian_for_learner,
    get_verified_guardian_profiles_queryset,
    guardian_has_access_to_learner,
)
from apps.users.selectors.invite_code_selectors import (
    get_active_invite_codes_queryset,
    get_available_invite_code_by_raw_code,
    get_available_invite_codes_queryset,
    get_guardian_curator_codes_for_group,
    get_guardian_learner_codes_for_user,
    get_invite_code_by_hash,
    get_invite_codes_queryset,
    get_teacher_registration_codes_for_organization,
)
from apps.users.selectors.learner_selectors import (
    get_learner_profile_by_id,
    get_learner_profile_by_user,
    get_learner_profiles_queryset,
    get_learners_by_curator,
    get_learners_by_department,
    get_learners_by_group,
    get_learners_by_organization,
    get_minor_learners_created_by_guardian,
    get_pending_learner_profiles_queryset,
    get_verified_learner_profiles_queryset,
)
from apps.users.selectors.profile_selectors import (
    get_profile_by_user,
    get_profiles_pending_avatar_moderation,
    get_profiles_pending_profile_moderation,
    get_profiles_queryset,
)
from apps.users.selectors.role_selectors import (
    get_active_roles_queryset,
    get_active_user_roles_queryset,
    get_guardian_reviewers,
    get_learner_reviewers,
    get_organization_reviewers,
    get_role_by_code,
    get_roles_queryset,
    get_teacher_reviewers,
    get_user_active_role_codes,
    get_user_active_roles,
    get_user_roles_queryset,
    user_has_active_role,
    user_is_superadmin,
)
from apps.users.selectors.teacher_selectors import (
    get_public_teacher_profiles_queryset,
    get_public_teachers_by_organization,
    get_teacher_profile_by_id,
    get_teacher_profile_by_user,
    get_teacher_profiles_queryset,
    get_teachers_by_department,
    get_teachers_by_organization,
    get_verified_teacher_profiles_queryset,
)
from apps.users.selectors.user_join_request_selectors import (
    get_join_request_by_id,
    get_join_requests_queryset,
    get_pending_guardian_requests_for_learner,
    get_pending_join_requests_for_reviewer,
    get_pending_join_requests_queryset,
    get_pending_learner_requests_for_group,
    get_pending_teacher_requests_for_organization,
    get_user_pending_join_requests,
    user_has_pending_join_request,
)
from apps.users.selectors.user_selectors import (
    get_active_users_queryset,
    get_blocked_users_queryset,
    get_managed_accounts_for_guardian,
    get_user_by_email,
    get_user_by_id,
    get_user_by_phone,
    get_users_pending_email_queryset,
    get_users_pending_review_queryset,
    get_users_queryset,
    get_users_scheduled_for_deletion_queryset,
    user_email_exists,
    user_phone_exists,
)

__all__ = [
    "get_active_guardian_learner_links_queryset",
    "get_active_guardian_link",
    "get_active_invite_codes_queryset",
    "get_active_roles_queryset",
    "get_active_user_roles_queryset",
    "get_active_users_queryset",
    "get_audit_logs_by_action",
    "get_audit_logs_by_actor",
    "get_audit_logs_for_user",
    "get_available_invite_code_by_raw_code",
    "get_available_invite_codes_queryset",
    "get_blocked_users_queryset",
    "get_guardian_curator_codes_for_group",
    "get_guardian_learner_codes_for_user",
    "get_guardian_learner_links_queryset",
    "get_guardian_link",
    "get_guardian_profile_by_user",
    "get_guardian_profiles_queryset",
    "get_guardian_reviewers",
    "get_guardians_for_learner",
    "get_invite_code_by_hash",
    "get_invite_codes_queryset",
    "get_join_request_by_id",
    "get_join_requests_queryset",
    "get_learner_profile_by_id",
    "get_learner_profile_by_user",
    "get_learner_profiles_queryset",
    "get_learner_reviewers",
    "get_learners_by_curator",
    "get_learners_by_department",
    "get_learners_by_group",
    "get_learners_by_organization",
    "get_learners_for_guardian",
    "get_managed_accounts_for_guardian",
    "get_minor_learners_created_by_guardian",
    "get_organization_reviewers",
    "get_pending_guardian_requests_for_learner",
    "get_pending_join_requests_for_reviewer",
    "get_pending_join_requests_queryset",
    "get_pending_learner_profiles_queryset",
    "get_pending_learner_requests_for_group",
    "get_pending_teacher_requests_for_organization",
    "get_primary_guardian_for_learner",
    "get_profile_by_user",
    "get_profiles_pending_avatar_moderation",
    "get_profiles_pending_profile_moderation",
    "get_profiles_queryset",
    "get_public_teacher_profiles_queryset",
    "get_public_teachers_by_organization",
    "get_registration_attempts_by_email_hash",
    "get_registration_attempts_by_ip",
    "get_registration_attempts_by_phone_hash",
    "get_registration_attempts_queryset",
    "get_role_by_code",
    "get_roles_queryset",
    "get_teacher_profile_by_id",
    "get_teacher_profile_by_user",
    "get_teacher_profiles_queryset",
    "get_teacher_reviewers",
    "get_teacher_registration_codes_for_organization",
    "get_teachers_by_department",
    "get_teachers_by_organization",
    "get_user_active_role_codes",
    "get_user_active_roles",
    "get_user_audit_logs_queryset",
    "get_user_by_email",
    "get_user_by_id",
    "get_user_by_phone",
    "get_user_pending_join_requests",
    "get_user_roles_queryset",
    "get_users_pending_email_queryset",
    "get_users_pending_review_queryset",
    "get_users_queryset",
    "get_users_scheduled_for_deletion_queryset",
    "get_verified_guardian_profiles_queryset",
    "get_verified_learner_profiles_queryset",
    "get_verified_teacher_profiles_queryset",
    "guardian_has_access_to_learner",
    "user_email_exists",
    "user_has_active_role",
    "user_has_pending_join_request",
    "user_is_superadmin",
    "user_phone_exists",
    "get_active_role_code_for_user",
    "get_current_role_profile",
    "get_or_create_profile_for_user",
    "get_role_label",
]
