# Generated by Django 5.2.14 on 2026-06-07 17:22

import uuid

import apps.course.validators.course_plan_validators
import apps.course.validators.course_progress_validators
import apps.course.validators.course_structure_validators
import apps.course.validators.course_validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("education", "0001_initial"),
        ("organizations", "0003_groupcurator_teacherorganization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaterialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("course", "Курс"),
                            ("section", "Раздел"),
                            ("lesson", "Урок"),
                        ],
                        default="course",
                        max_length=32,
                        verbose_name="Размещение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            apps.course.validators.course_structure_validators.validate_order_value
                        ],
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="Обязательный материал"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="Виден")),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Материал курса",
                "verbose_name_plural": "Материалы курса",
                "db_table": "course_material_link",
                "ordering": (
                    "course",
                    "section__order",
                    "lesson__order",
                    "order",
                    "id",
                ),
            },
        ),
        migrations.CreateModel(
            name="CoursePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discipline_name",
                    models.CharField(
                        max_length=255,
                        verbose_name="Название дисциплины / МДК / практики",
                    ),
                ),
                (
                    "discipline_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код дисциплины"
                    ),
                ),
                (
                    "specialty_code",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Код специальности / профессии",
                    ),
                ),
                (
                    "specialty_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Наименование специальности / профессии",
                    ),
                ),
                (
                    "teacher_name_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Преподаватель в документе",
                    ),
                ),
                (
                    "organization_name_snapshot",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Организация в документе",
                    ),
                ),
                (
                    "academic_year_label",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name="Учебный год в документе",
                    ),
                ),
                (
                    "semester_number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Номер семестра"
                    ),
                ),
                (
                    "total_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего часов по учебному плану"
                    ),
                ),
                (
                    "semester_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Часов на семестр"
                    ),
                ),
                (
                    "theory_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Теоретические занятия"
                    ),
                ),
                (
                    "practice_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Практические занятия"
                    ),
                ),
                (
                    "lab_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Лабораторные занятия"
                    ),
                ),
                (
                    "self_study_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Самостоятельная работа"
                    ),
                ),
                (
                    "consultation_hours",
                    models.PositiveIntegerField(default=0, verbose_name="Консультации"),
                ),
                (
                    "commission_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Предметная / цикловая комиссия",
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Номер протокола"
                    ),
                ),
                (
                    "protocol_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата протокола"
                    ),
                ),
                (
                    "approved_order_number",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Номер приказа утверждения",
                    ),
                ),
                (
                    "approved_order_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата приказа утверждения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("imported", "Импортирован"),
                            ("reviewed", "Проверен"),
                            ("approved", "Утверждён"),
                            ("archived", "Архивирован"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="Статус КТП",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "КТП курса",
                "verbose_name_plural": "КТП курсов",
                "db_table": "course_plan",
                "ordering": ("course__organization", "course__subject", "-updated_at"),
            },
        ),
        migrations.CreateModel(
            name="CoursePlanImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        upload_to="course/ktp/",
                        validators=[
                            apps.course.validators.course_plan_validators.validate_course_plan_file_extension
                        ],
                        verbose_name="Файл КТП",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Исходное имя файла"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Хэш файла"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Загружен"),
                            ("parsed", "Разобран"),
                            ("failed", "Ошибка"),
                            ("applied", "Применён"),
                        ],
                        default="uploaded",
                        max_length=32,
                        verbose_name="Статус импорта",
                    ),
                ),
                (
                    "parser_version",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Версия парсера"
                    ),
                ),
                (
                    "parsed_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Результат разбора"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Ошибки разбора"
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата применения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Импорт КТП",
                "verbose_name_plural": "Импорты КТП",
                "db_table": "course_plan_import",
                "ordering": ("-imported_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_lessons_count",
                    models.PositiveIntegerField(default=0, verbose_name="Всего уроков"),
                ),
                (
                    "completed_lessons_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Завершено уроков"
                    ),
                ),
                (
                    "required_lessons_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Обязательных уроков"
                    ),
                ),
                (
                    "completed_required_lessons_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Завершено обязательных уроков"
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            apps.course.validators.course_progress_validators.validate_progress_percent
                        ],
                        verbose_name="Прогресс, %",
                    ),
                ),
                (
                    "spent_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Затрачено минут"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Прогресс курса",
                "verbose_name_plural": "Прогресс курсов",
                "db_table": "course_progress",
                "ordering": ("-last_activity_at", "-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название раздела"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "section_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер раздела"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            apps.course.validators.course_structure_validators.validate_order_value
                        ],
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "planned_hours",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            apps.course.validators.course_structure_validators.validate_hours_value
                        ],
                        verbose_name="Плановые часы",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, verbose_name="Обязательный раздел"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Раздел курса",
                "verbose_name_plural": "Разделы курса",
                "db_table": "course_section",
                "ordering": ("course", "order", "section_number", "title"),
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начат"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершён"),
                            ("skipped", "Пропущен"),
                        ],
                        default="not_started",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний просмотр"
                    ),
                ),
                (
                    "spent_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Затрачено минут"
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество попыток"
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            apps.course.validators.course_progress_validators.validate_score_value
                        ],
                        verbose_name="Балл",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Прогресс урока",
                "verbose_name_plural": "Прогресс уроков",
                "db_table": "course_lesson_progress",
                "ordering": (
                    "lesson__section__order",
                    "lesson__order",
                    "lesson__lesson_number",
                ),
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный идентификатор",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            apps.course.validators.course_validators.validate_course_code
                        ],
                        verbose_name="Код курса",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=120,
                        unique=True,
                        validators=[
                            apps.course.validators.course_validators.validate_course_slug
                        ],
                        verbose_name="Slug",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Краткий подзаголовок"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("academic", "Академический"),
                            ("author", "Авторский"),
                            ("exam_prep", "Подготовка к экзамену"),
                            ("intensive", "Интенсив"),
                            ("club", "Кружок / клуб"),
                            ("elective", "Факультатив"),
                        ],
                        default="academic",
                        max_length=32,
                        verbose_name="Тип курса",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("manual", "Создан вручную"),
                            ("ktp_import", "Импортирован из КТП"),
                            ("education_load", "Создан из нагрузки"),
                            ("template", "Создан из шаблона"),
                        ],
                        default="manual",
                        max_length=32,
                        verbose_name="Источник курса",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликован"),
                            ("archived", "Архивирован"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Приватный"),
                            ("assigned_only", "Только назначенным"),
                            ("organization", "Внутри организации"),
                            ("public_link", "По публичной ссылке"),
                        ],
                        default="private",
                        max_length=32,
                        verbose_name="Видимость",
                    ),
                ),
                (
                    "level",
                    models.CharField(blank=True, max_length=64, verbose_name="Уровень"),
                ),
                (
                    "language",
                    models.CharField(
                        default="ru", max_length=16, verbose_name="Язык курса"
                    ),
                ),
                (
                    "cover_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="course/covers/",
                        verbose_name="Обложка курса",
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(default=False, verbose_name="Шаблон курса"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "allow_self_enrollment",
                    models.BooleanField(
                        default=False, verbose_name="Разрешить самостоятельную запись"
                    ),
                ),
                (
                    "enrollment_code",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Код записи",
                    ),
                ),
                (
                    "starts_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала курса"
                    ),
                ),
                (
                    "ends_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания курса"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата архивации"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="education.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "owner_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец-преподаватель",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="education.educationperiod",
                        verbose_name="Учебный период",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="organizations.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "db_table": "course_course",
                "ordering": ("organization", "subject", "-updated_at", "title"),
            },
        ),
        migrations.CreateModel(
            name="CourseAccessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("learner", "Персональный доступ"),
                            ("organization", "Доступ организации"),
                            ("public_link", "Публичная ссылка"),
                            ("invite_code", "Код приглашения"),
                        ],
                        max_length=32,
                        verbose_name="Тип доступа",
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код доступа"
                    ),
                ),
                (
                    "starts_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала доступа"
                    ),
                ),
                (
                    "ends_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания доступа"
                    ),
                ),
                (
                    "auto_enroll",
                    models.BooleanField(
                        default=False, verbose_name="Автоматически записывать"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="course.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_access_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обучающийся",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_access_rules",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило доступа к курсу",
                "verbose_name_plural": "Правила доступа к курсам",
                "db_table": "course_access_rule",
                "ordering": ("course", "access_type", "id"),
            },
        ),
        migrations.CreateModel(
            name="CourseGroupAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("hidden", "Скрыт"),
                            ("visible", "Виден"),
                            ("archived", "Архивирован"),
                        ],
                        default="hidden",
                        max_length=32,
                        verbose_name="Видимость для группы",
                    ),
                ),
                (
                    "starts_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала доступа"
                    ),
                ),
                (
                    "ends_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания доступа"
                    ),
                ),
                (
                    "auto_enroll",
                    models.BooleanField(
                        default=True, verbose_name="Автоматически записывать учащихся"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_accesses",
                        to="course.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_accesses",
                        to="organizations.studygroup",
                        verbose_name="Учебная группа",
                    ),
                ),
                (
                    "group_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_group_accesses",
                        to="education.groupsubject",
                        verbose_name="Предмет группы",
                    ),
                ),
                (
                    "teacher_group_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_group_accesses",
                        to="education.teachergroupsubject",
                        verbose_name="Назначение преподавателя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ группы к курсу",
                "verbose_name_plural": "Доступы групп к курсам",
                "db_table": "course_group_access",
                "ordering": ("course", "group__name", "group__code"),
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Зачислен"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершён"),
                            ("cancelled", "Отменён"),
                            ("archived", "Архивирован"),
                        ],
                        default="enrolled",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата записи"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            apps.course.validators.course_progress_validators.validate_progress_percent
                        ],
                        verbose_name="Прогресс, %",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "access_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="course.courseaccessrule",
                        verbose_name="Правило доступа",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="course.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обучающийся",
                    ),
                ),
                (
                    "group_access",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to="course.coursegroupaccess",
                        verbose_name="Групповой доступ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на курс",
                "verbose_name_plural": "Записи на курсы",
                "db_table": "course_enrollment",
                "ordering": ("-last_activity_at", "-enrolled_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер занятия"
                    ),
                ),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Урок"),
                            ("lecture", "Лекция"),
                            ("practice", "Практическое занятие"),
                            ("lab", "Лабораторная работа"),
                            ("seminar", "Семинар"),
                            ("control", "Контрольная работа"),
                            ("consultation", "Консультация"),
                            ("independent", "Самостоятельная работа"),
                            ("other", "Иное занятие"),
                        ],
                        default="lesson",
                        max_length=32,
                        verbose_name="Вид занятия",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Тема занятия"),
                ),
                (
                    "short_content",
                    models.TextField(blank=True, verbose_name="Краткое содержание"),
                ),
                (
                    "planned_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Плановые часы"
                    ),
                ),
                (
                    "theory_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Теоретические часы"
                    ),
                ),
                (
                    "practice_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Практические часы"
                    ),
                ),
                (
                    "lab_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Лабораторные часы"
                    ),
                ),
                (
                    "self_study_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Самостоятельная работа"
                    ),
                ),
                (
                    "visual_aids",
                    models.TextField(
                        blank=True, verbose_name="Наглядные пособия и приборы"
                    ),
                ),
                (
                    "literature",
                    models.TextField(blank=True, verbose_name="Учебники и литература"),
                ),
                (
                    "independent_work",
                    models.TextField(
                        blank=True, verbose_name="Задания для самостоятельной работы"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            apps.course.validators.course_structure_validators.validate_order_value
                        ],
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "available_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Доступен с"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Обязательный урок"),
                ),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False, verbose_name="Доступен для предпросмотра"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="course.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок курса",
                "verbose_name_plural": "Уроки курса",
                "db_table": "course_lesson",
                "ordering": ("course", "section__order", "order", "lesson_number"),
            },
        ),
        migrations.CreateModel(
            name="CourseLessonBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("video", "Видео"),
                            ("file", "Файл"),
                            ("link", "Ссылка"),
                            ("image", "Изображение"),
                            ("presentation", "Презентация"),
                            ("code", "Код"),
                            ("embed", "Встраиваемый блок"),
                            ("material", "Материал"),
                            ("assignment_placeholder", "Место для задания"),
                        ],
                        default="text",
                        max_length=32,
                        verbose_name="Тип блока",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок блока"
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Содержимое")),
                (
                    "external_url",
                    models.URLField(blank=True, verbose_name="Внешняя ссылка"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            apps.course.validators.course_structure_validators.validate_order_value
                        ],
                        verbose_name="Порядок",
                    ),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="Виден")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="course.courselesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блок урока",
                "verbose_name_plural": "Блоки уроков",
                "db_table": "course_lesson_block",
                "ordering": ("lesson", "order", "id"),
            },
        ),
    ]
