# Generated by Django 5.2.14 on 2026-06-07 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("materials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courselessonblock",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_lesson_blocks",
                to="materials.material",
                verbose_name="Материал",
            ),
        ),
        migrations.AddField(
            model_name="coursemateriallink",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_links",
                to="course.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="coursemateriallink",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_links",
                to="course.courselesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AddField(
            model_name="coursemateriallink",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_links",
                to="materials.material",
                verbose_name="Материал",
            ),
        ),
        migrations.AddField(
            model_name="courseplan",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan",
                to="course.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="courseplanimport",
            name="course_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imports",
                to="course.courseplan",
                verbose_name="КТП",
            ),
        ),
        migrations.AddField(
            model_name="courseplanimport",
            name="imported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_plan_imports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем загружен",
            ),
        ),
        migrations.AddField(
            model_name="courseprogress",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="course.courseenrollment",
                verbose_name="Запись на курс",
            ),
        ),
        migrations.AddField(
            model_name="courseprogress",
            name="last_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_course_progresses",
                to="course.courselesson",
                verbose_name="Последний урок",
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="course.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="coursemateriallink",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_links",
                to="course.coursesection",
                verbose_name="Раздел",
            ),
        ),
        migrations.AddField(
            model_name="courselesson",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="course.coursesection",
                verbose_name="Раздел",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="course_progress",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progresses",
                to="course.courseprogress",
                verbose_name="Прогресс курса",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progresses",
                to="course.courseenrollment",
                verbose_name="Запись на курс",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progresses",
                to="course.courselesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["status"], name="course_course_status_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["visibility"], name="course_course_visibility_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["course_type"], name="course_course_type_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["owner_teacher"], name="course_course_teacher_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["organization"], name="course_course_org_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["subject"], name="course_course_subject_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["academic_year"], name="course_course_year_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["period"], name="course_course_period_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["is_active"], name="course_course_active_idx"),
        ),
        migrations.AddIndex(
            model_name="courseaccessrule",
            index=models.Index(fields=["course"], name="course_access_rule_course_idx"),
        ),
        migrations.AddIndex(
            model_name="courseaccessrule",
            index=models.Index(
                fields=["access_type"], name="course_access_rule_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseaccessrule",
            index=models.Index(
                fields=["learner"], name="course_access_rule_learner_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseaccessrule",
            index=models.Index(
                fields=["organization"], name="course_access_rule_org_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseaccessrule",
            index=models.Index(
                fields=["is_active"], name="course_access_rule_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseaccessrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("access_type", "learner"), ("learner__isnull", False)
                ),
                fields=("course", "learner"),
                name="course_unique_learner_access_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseaccessrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("access_type", "organization"), ("organization__isnull", False)
                ),
                fields=("course", "organization"),
                name="course_unique_org_access_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseaccessrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(
                        ("access_type", "public_link"),
                        ("access_type", "invite_code"),
                        _connector="OR",
                    ),
                    models.Q(("access_code", ""), _negated=True),
                ),
                fields=("access_code",),
                name="course_unique_access_code_rule",
            ),
        ),
        migrations.AddIndex(
            model_name="coursegroupaccess",
            index=models.Index(
                fields=["course"], name="course_group_access_course_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursegroupaccess",
            index=models.Index(fields=["group"], name="course_group_access_group_idx"),
        ),
        migrations.AddIndex(
            model_name="coursegroupaccess",
            index=models.Index(
                fields=["visibility"], name="course_group_access_vis_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursegroupaccess",
            index=models.Index(
                fields=["is_active"], name="course_group_access_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegroupaccess",
            constraint=models.UniqueConstraint(
                fields=("course", "group"), name="course_unique_group_access"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursegroupaccess",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group_subject__isnull", False)),
                fields=("course", "group_subject"),
                name="course_unique_group_subject_access",
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(fields=["course"], name="course_enrollment_course_idx"),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(
                fields=["learner"], name="course_enrollment_learner_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(fields=["status"], name="course_enrollment_status_idx"),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(fields=["group_access"], name="course_enroll_group_idx"),
        ),
        migrations.AddIndex(
            model_name="courseenrollment",
            index=models.Index(fields=["access_rule"], name="course_enroll_rule_idx"),
        ),
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.UniqueConstraint(
                fields=("course", "learner"), name="course_unique_learner_enrollment"
            ),
        ),
        migrations.AddIndex(
            model_name="courselessonblock",
            index=models.Index(fields=["lesson"], name="course_block_lesson_idx"),
        ),
        migrations.AddIndex(
            model_name="courselessonblock",
            index=models.Index(fields=["block_type"], name="course_block_type_idx"),
        ),
        migrations.AddIndex(
            model_name="courselessonblock",
            index=models.Index(fields=["is_visible"], name="course_block_visible_idx"),
        ),
        migrations.AddConstraint(
            model_name="courselessonblock",
            constraint=models.UniqueConstraint(
                fields=("lesson", "order"), name="course_unique_lesson_block_order"
            ),
        ),
        migrations.AddIndex(
            model_name="courseplan",
            index=models.Index(fields=["status"], name="course_plan_status_idx"),
        ),
        migrations.AddIndex(
            model_name="courseplan",
            index=models.Index(fields=["is_active"], name="course_plan_active_idx"),
        ),
        migrations.AddIndex(
            model_name="courseplan",
            index=models.Index(fields=["semester_number"], name="course_plan_sem_idx"),
        ),
        migrations.AddIndex(
            model_name="courseplanimport",
            index=models.Index(fields=["status"], name="course_plan_import_status_idx"),
        ),
        migrations.AddIndex(
            model_name="courseplanimport",
            index=models.Index(
                fields=["course_plan"], name="course_plan_import_plan_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseplanimport",
            index=models.Index(
                fields=["imported_by"], name="course_plan_import_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseprogress",
            index=models.Index(
                fields=["progress_percent"], name="course_progress_percent_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseprogress",
            index=models.Index(
                fields=["last_activity_at"], name="course_progress_activity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursesection",
            index=models.Index(fields=["course"], name="course_section_course_idx"),
        ),
        migrations.AddIndex(
            model_name="coursesection",
            index=models.Index(fields=["order"], name="course_section_order_idx"),
        ),
        migrations.AddIndex(
            model_name="coursesection",
            index=models.Index(fields=["is_published"], name="course_section_pub_idx"),
        ),
        migrations.AddIndex(
            model_name="coursesection",
            index=models.Index(fields=["is_active"], name="course_section_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="coursesection",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="course_unique_section_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursesection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("section_number__isnull", False)),
                fields=("course", "section_number"),
                name="course_unique_section_number",
            ),
        ),
        migrations.AddIndex(
            model_name="coursemateriallink",
            index=models.Index(fields=["course"], name="course_material_course_idx"),
        ),
        migrations.AddIndex(
            model_name="coursemateriallink",
            index=models.Index(fields=["section"], name="course_material_section_idx"),
        ),
        migrations.AddIndex(
            model_name="coursemateriallink",
            index=models.Index(fields=["lesson"], name="course_material_lesson_idx"),
        ),
        migrations.AddIndex(
            model_name="coursemateriallink",
            index=models.Index(
                fields=["material"], name="course_material_material_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursemateriallink",
            index=models.Index(fields=["placement"], name="course_material_place_idx"),
        ),
        migrations.AddIndex(
            model_name="coursemateriallink",
            index=models.Index(
                fields=["is_visible"], name="course_material_visible_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursemateriallink",
            constraint=models.UniqueConstraint(
                fields=("course", "section", "lesson", "material"),
                name="course_unique_material_link",
            ),
        ),
        migrations.AddIndex(
            model_name="courselesson",
            index=models.Index(fields=["course"], name="course_lesson_course_idx"),
        ),
        migrations.AddIndex(
            model_name="courselesson",
            index=models.Index(fields=["section"], name="course_lesson_section_idx"),
        ),
        migrations.AddIndex(
            model_name="courselesson",
            index=models.Index(fields=["lesson_type"], name="course_lesson_type_idx"),
        ),
        migrations.AddIndex(
            model_name="courselesson",
            index=models.Index(fields=["is_published"], name="course_lesson_pub_idx"),
        ),
        migrations.AddIndex(
            model_name="courselesson",
            index=models.Index(fields=["is_active"], name="course_lesson_active_idx"),
        ),
        migrations.AddIndex(
            model_name="courselesson",
            index=models.Index(fields=["order"], name="course_lesson_order_idx"),
        ),
        migrations.AddConstraint(
            model_name="courselesson",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lesson_number__isnull", False)),
                fields=("course", "lesson_number"),
                name="course_unique_lesson_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="courselesson",
            constraint=models.UniqueConstraint(
                condition=models.Q(("section__isnull", False)),
                fields=("section", "order"),
                name="course_unique_lesson_order_in_section",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["enrollment"], name="course_lesson_prog_enroll_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["course_progress"], name="course_lesson_prog_course_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(fields=["lesson"], name="course_lesson_prog_lesson_idx"),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(fields=["status"], name="course_lesson_prog_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "lesson"), name="course_unique_lesson_progress"
            ),
        ),
    ]
