# Generated by Django 5.2.14 on 2026-06-07 09:31

import apps.education.validators.education_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_groupcurator_teacherorganization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: 2025/2026.",
                        max_length=32,
                        unique=True,
                        validators=[
                            apps.education.validators.education_validators.validate_academic_year_name
                        ],
                        verbose_name="Название учебного года",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, verbose_name="Текущий учебный год"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Учебный год",
                "verbose_name_plural": "Учебные годы",
                "db_table": "education_academic_year",
                "ordering": ("-start_date",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="education_unique_current_academic_year",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64,
                        validators=[
                            apps.education.validators.education_validators.validate_curriculum_code
                        ],
                        verbose_name="Код учебного плана",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название учебного плана"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "total_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Можно оставить пустым и считать сумму по элементам плана.",
                        null=True,
                        verbose_name="Общее количество часов",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активен"),
                            ("archived", "Архивирован"),
                        ],
                        default="draft",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curricula",
                        to="education.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curricula",
                        to="organizations.department",
                        verbose_name="Отделение",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curricula",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный план",
                "verbose_name_plural": "Учебные планы",
                "db_table": "education_curriculum",
                "ordering": ("organization", "-academic_year__start_date", "name"),
            },
        ),
        migrations.CreateModel(
            name="EducationPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название периода"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=64,
                        validators=[
                            apps.education.validators.education_validators.validate_period_code
                        ],
                        verbose_name="Код периода",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("year", "Год"),
                            ("semester", "Семестр"),
                            ("trimester", "Триместр"),
                            ("quarter", "Четверть"),
                            ("module", "Модуль"),
                            ("other", "Иной период"),
                        ],
                        default="semester",
                        max_length=32,
                        verbose_name="Тип периода",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Порядковый номер"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Текущий период"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="education.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный период",
                "verbose_name_plural": "Учебные периоды",
                "db_table": "education_period",
                "ordering": ("academic_year", "sequence", "start_date"),
            },
        ),
        migrations.CreateModel(
            name="CurriculumItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Порядковый номер"
                    ),
                ),
                (
                    "planned_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Плановые часы"
                    ),
                ),
                (
                    "contact_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Контактные часы"
                    ),
                ),
                (
                    "independent_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Самостоятельная работа"
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("none", "Без аттестации"),
                            ("pass_fail", "Зачёт / незачёт"),
                            ("credit", "Зачёт"),
                            ("exam", "Экзамен"),
                            ("test", "Тестирование"),
                            ("project", "Проект"),
                            ("other", "Иная форма"),
                        ],
                        default="none",
                        max_length=32,
                        verbose_name="Форма аттестации",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, verbose_name="Обязательный элемент"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="education.curriculum",
                        verbose_name="Учебный план",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_items",
                        to="organizations.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_items",
                        to="education.educationperiod",
                        verbose_name="Учебный период",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент учебного плана",
                "verbose_name_plural": "Элементы учебного плана",
                "db_table": "education_curriculum_item",
                "ordering": ("curriculum", "period__sequence", "sequence", "subject"),
            },
        ),
        migrations.CreateModel(
            name="GroupSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planned_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Плановые часы"
                    ),
                ),
                (
                    "contact_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Контактные часы"
                    ),
                ),
                (
                    "independent_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Самостоятельная работа"
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("none", "Без аттестации"),
                            ("pass_fail", "Зачёт / незачёт"),
                            ("credit", "Зачёт"),
                            ("exam", "Экзамен"),
                            ("test", "Тестирование"),
                            ("project", "Проект"),
                            ("other", "Иная форма"),
                        ],
                        default="none",
                        max_length=32,
                        verbose_name="Форма аттестации",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, verbose_name="Обязательный предмет"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_subjects",
                        to="education.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
                (
                    "curriculum_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group_subjects",
                        to="education.curriculumitem",
                        verbose_name="Элемент учебного плана",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_subjects",
                        to="organizations.studygroup",
                        verbose_name="Учебная группа",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_subjects",
                        to="education.educationperiod",
                        verbose_name="Учебный период",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_subjects",
                        to="organizations.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет группы",
                "verbose_name_plural": "Предметы групп",
                "db_table": "education_group_subject",
                "ordering": ("group", "period__sequence", "subject"),
            },
        ),
        migrations.CreateModel(
            name="LearnerGroupEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_date", models.DateField(verbose_name="Дата зачисления")),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата завершения / выбытия"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активно"),
                            ("transferred", "Переведён"),
                            ("suspended", "Приостановлено"),
                            ("graduated", "Завершено"),
                            ("expelled", "Отчислен"),
                            ("archived", "Архивировано"),
                        ],
                        default="active",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True, verbose_name="Основное зачисление"
                    ),
                ),
                (
                    "journal_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер в журнале"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learner_enrollments",
                        to="education.academicyear",
                        verbose_name="Учебный год",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_enrollments",
                        to="organizations.studygroup",
                        verbose_name="Учебная группа",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_group_enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обучающийся",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зачисление обучающегося в группу",
                "verbose_name_plural": "Зачисления обучающихся в группы",
                "db_table": "education_learner_group_enrollment",
                "ordering": ("-academic_year__start_date", "group", "learner"),
            },
        ),
        migrations.CreateModel(
            name="TeacherGroupSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Основной преподаватель"),
                            ("assistant", "Ассистент"),
                            ("substitute", "Замещающий преподаватель"),
                            ("other", "Иная роль"),
                        ],
                        default="primary",
                        max_length=32,
                        verbose_name="Роль преподавателя",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True, verbose_name="Основной преподаватель"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "planned_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Плановые часы преподавателя"
                    ),
                ),
                (
                    "starts_at",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "ends_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "group_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="education.groupsubject",
                        verbose_name="Предмет группы",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_group_subjects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Преподаватель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение преподавателя на предмет группы",
                "verbose_name_plural": "Назначения преподавателей на предметы групп",
                "db_table": "education_teacher_group_subject",
                "ordering": ("group_subject", "-is_primary", "teacher"),
            },
        ),
        migrations.AddConstraint(
            model_name="curriculum",
            constraint=models.UniqueConstraint(
                fields=("organization", "academic_year", "code"),
                name="education_unique_curriculum_code_per_org_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="educationperiod",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "code"),
                name="education_unique_period_code_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="educationperiod",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "sequence"),
                name="education_unique_period_sequence_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="educationperiod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("academic_year", "is_current"),
                name="education_unique_current_period_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumitem",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "period", "subject"),
                name="education_unique_subject_per_curriculum_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumitem",
            constraint=models.UniqueConstraint(
                fields=("curriculum", "period", "sequence"),
                name="education_unique_sequence_per_curriculum_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupsubject",
            constraint=models.UniqueConstraint(
                fields=("group", "subject", "academic_year", "period"),
                name="education_unique_group_subject_per_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="learnergroupenrollment",
            constraint=models.UniqueConstraint(
                fields=("learner", "group", "academic_year"),
                name="education_unique_learner_group_enrollment_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="learnergroupenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("learner", "academic_year", "is_primary"),
                name="education_unique_primary_learner_enrollment_per_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="learnergroupenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("journal_number__isnull", False)),
                fields=("group", "academic_year", "journal_number"),
                name="education_unique_journal_number_per_group_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="teachergroupsubject",
            constraint=models.UniqueConstraint(
                fields=("teacher", "group_subject"),
                name="education_unique_teacher_group_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="teachergroupsubject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("group_subject", "is_primary"),
                name="education_unique_primary_teacher_per_group_subject",
            ),
        ),
    ]
