# Generated by Django 5.2.14 on 2026-05-16 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Краткое название"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Код организации",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Образовательная организация",
                "verbose_name_plural": "Образовательные организации",
                "db_table": "organizations_organization",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Краткое название"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Код отделения",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="organizations.organization",
                        verbose_name="Образовательная организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отделение",
                "verbose_name_plural": "Отделения",
                "db_table": "organizations_department",
                "ordering": ("organization", "name"),
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Код группы",
                    ),
                ),
                (
                    "admission_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год поступления"
                    ),
                ),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="В архиве"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_groups",
                        to="organizations.department",
                        verbose_name="Отделение",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_groups",
                        to="organizations.organization",
                        verbose_name="Образовательная организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебная группа",
                "verbose_name_plural": "Учебные группы",
                "db_table": "organizations_study_group",
                "ordering": ("organization", "name"),
            },
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="organizations_department_unique_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="studygroup",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="organizations_study_group_unique_name",
            ),
        ),
    ]
