# Generated by Django 5.2.14 on 2026-05-18 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Краткое название"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Код предмета",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный предмет",
                "verbose_name_plural": "Учебные предметы",
                "db_table": "organizations_subject",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Основной предмет"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь преподавателя с предметом",
                "verbose_name_plural": "Связи преподавателей с предметами",
                "db_table": "organizations_teacher_subject",
                "ordering": ("teacher", "-is_primary", "subject__name"),
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(blank=True, max_length=150, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_default_public",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Используется для незарегистрированных пользователей на странице преподавателей.",
                verbose_name="Организация по умолчанию для публичной зоны",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_public",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Показывать публично"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organizations/logos/%Y/%m/",
                verbose_name="Логотип",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
        ),
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Человекочитаемый идентификатор для публичных URL.",
                max_length=160,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, verbose_name="Сайт"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active", "is_public"], name="organizations_org_public_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_default_public", "is_active"],
                name="organizations_org_default_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                fields=("name",), name="organizations_organization_unique_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default_public", True)),
                fields=("is_default_public",),
                name="organizations_organization_single_default_public",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["is_active", "name"], name="org_subj_active_idx"
            ),
        ),
        migrations.AddField(
            model_name="teachersubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_links",
                to="organizations.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="teachersubject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_subjects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubject",
            index=models.Index(
                fields=["teacher", "is_active"], name="org_ts_teacher_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubject",
            index=models.Index(
                fields=["subject", "is_active"], name="org_ts_subject_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachersubject",
            constraint=models.UniqueConstraint(
                fields=("teacher", "subject"), name="org_teacher_subject_unique"
            ),
        ),
    ]
