# Generated by Django 5.2.14 on 2026-06-06 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_subject_teachersubject_organization_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCurator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Основной куратор"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "starts_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала кураторства"
                    ),
                ),
                (
                    "ends_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания кураторства"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
            ],
            options={
                "verbose_name": "Куратор группы",
                "verbose_name_plural": "Кураторы групп",
                "db_table": "organizations_group_curator",
                "ordering": ("group", "-is_primary", "teacher"),
            },
        ),
        migrations.CreateModel(
            name="TeacherOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Должность"
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Основное место работы"),
                            ("part_time", "Совместительство"),
                            ("contract", "Договор"),
                            ("other", "Иное"),
                        ],
                        default="full_time",
                        max_length=32,
                        verbose_name="Тип занятости",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="Основная организация"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "starts_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала работы"
                    ),
                ),
                (
                    "ends_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания работы"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
            ],
            options={
                "verbose_name": "Организация преподавателя",
                "verbose_name_plural": "Организации преподавателей",
                "db_table": "organizations_teacher_organization",
                "ordering": ("teacher", "-is_primary", "organization"),
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ("name",),
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.AlterModelOptions(
            name="teachersubject",
            options={
                "ordering": ("teacher", "-is_primary", "subject"),
                "verbose_name": "Предмет преподавателя",
                "verbose_name_plural": "Предметы преподавателей",
            },
        ),
        migrations.RemoveConstraint(
            model_name="teachersubject",
            name="org_teacher_subject_unique",
        ),
        migrations.RenameIndex(
            model_name="subject",
            new_name="org_subject_active_name_idx",
            old_name="org_subj_active_idx",
        ),
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="organization",
            name="teacher_registration_code_expires_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Код регистрации преподавателя истекает",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="teacher_registration_code_hash",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Хэш кода регистрации преподавателя",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="teacher_registration_code_is_active",
            field=models.BooleanField(
                default=False, verbose_name="Код регистрации преподавателя активен"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="course_number",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Курс"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="join_code_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Код вступления в группу истекает"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="join_code_hash",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Хэш кода вступления в группу"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="join_code_is_active",
            field=models.BooleanField(
                default=False, verbose_name="Код вступления в группу активен"
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активна"),
                    ("archived", "Архивирована"),
                    ("graduated", "Выпущена"),
                    ("closed", "Закрыта"),
                ],
                db_index=True,
                default="active",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="studygroup",
            name="study_form",
            field=models.CharField(
                choices=[
                    ("full_time", "Очная"),
                    ("part_time", "Очно-заочная"),
                    ("extramural", "Заочная"),
                    ("distance", "Дистанционная"),
                    ("other", "Иная"),
                ],
                default="full_time",
                max_length=32,
                verbose_name="Форма обучения",
            ),
        ),
        migrations.AddField(
            model_name="teachersubject",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Заметки"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="teachersubject",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="teachersubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_subjects",
                to="organizations.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["organization", "is_active"], name="org_department_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["organization", "code"], name="org_department_code_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(
                fields=["organization", "status"], name="org_study_group_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(
                fields=["organization", "is_active"], name="org_study_group_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studygroup",
            index=models.Index(
                fields=["department", "status"], name="org_sg_dept_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["code", "is_active"], name="org_subject_code_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubject",
            index=models.Index(
                fields=["teacher", "is_primary"], name="org_ts_primary_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("organization", "code"),
                name="organizations_department_unique_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="studygroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("organization", "code"),
                name="organizations_study_group_unique_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="teachersubject",
            constraint=models.UniqueConstraint(
                fields=("teacher", "subject"),
                name="organizations_teacher_subject_unique",
            ),
        ),
        migrations.AddField(
            model_name="groupcurator",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curators",
                to="organizations.studygroup",
                verbose_name="Учебная группа",
            ),
        ),
        migrations.AddField(
            model_name="groupcurator",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="curated_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Куратор",
            ),
        ),
        migrations.AddField(
            model_name="teacherorganization",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_organizations",
                to="organizations.organization",
                verbose_name="Образовательная организация",
            ),
        ),
        migrations.AddField(
            model_name="teacherorganization",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_organizations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AddIndex(
            model_name="groupcurator",
            index=models.Index(
                fields=["group", "is_active"], name="org_group_curator_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupcurator",
            index=models.Index(
                fields=["teacher", "is_active"], name="org_curator_teacher_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupcurator",
            index=models.Index(
                fields=["group", "is_primary"], name="org_group_curator_primary_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupcurator",
            constraint=models.UniqueConstraint(
                fields=("group", "teacher"),
                name="organizations_group_curator_unique_teacher",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherorganization",
            index=models.Index(
                fields=["teacher", "is_active"], name="org_teacher_org_teacher_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherorganization",
            index=models.Index(
                fields=["organization", "is_active"], name="org_teacher_org_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherorganization",
            index=models.Index(
                fields=["teacher", "is_primary"], name="org_teacher_org_primary_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherorganization",
            constraint=models.UniqueConstraint(
                fields=("teacher", "organization"),
                name="organizations_teacher_org_unique_teacher",
            ),
        ),
    ]
